#!/usr/bin/env node
// Generates dist/inlined.mjs by concatenating cpp_loader.mjs +
// cpp_wasi_shim.mjs + the inlined wasm into one file. True single-file
// bundle: no relative imports inside dist/.
//
// tape_codec.mjs is intentionally NOT inlined — it's only needed by the
// optional capnwasm/tape entrypoint. Pulling it in here would bloat both
// inlined bundles by ~3 KB gzipped that nobody using `load()` directly
// needs. Users who want serialize/deserialize import them from
// `capnwasm/tape` separately, where bundlers can keep them out of
// browser bundles that don't reference them.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { gzipSync } from "node:zlib";

const ROOT = resolve(new URL("..", import.meta.url).pathname);

const wasm        = await readFile(resolve(ROOT, "zig-out", "capnp_cpp.opt.wasm"));
const wasiShim    = await readFile(resolve(ROOT, "js", "cpp_wasi_runtime.mjs"), "utf8");
const cppLoader   = await readFile(resolve(ROOT, "js", "cpp_loader.mjs"), "utf8");

// Strip relative imports — we're inlining all the dependencies.
const stripImports = (src) =>
  src.replace(/^import\s+\{[^}]+\}\s+from\s+["']\.\/[^"']+["'];?\s*$/gm, "");

// Pre-gzip the wasm and embed the gzipped bytes as base64. The single-file
// bundle's gzip-encoded delivery (npm pack ships .tgz; runtime servers
// gzip on the fly) won't double-compress meaningfully because base64 of
// already-compressed bytes has no exploitable structure — but the
// base64 of the GZIPPED wasm is dramatically shorter than base64 of raw
// wasm to begin with. Net win on both raw and on-wire bytes.
//
// At load time we gunzip via DecompressionStream("gzip"), which is
// universal: Node 18+, Cloudflare Workers, all modern browsers (Chrome
// 80+, Firefox 113+, Safari 16.4+). The decompression cost is sub-ms
// for ~110 KB of wasm — invisible behind the WebAssembly.compile that
// follows it.
const wasmGz = gzipSync(wasm, { level: 9 });

const bundle = `// capnwasm: single-file inlined bundle (cpp_loader + wasi shim + the
// wasm itself, gzipped + base64-encoded). One import, one fetch.
//
// Generated by js/build_inlined.mjs from cpp/build.sh — do not edit by hand.

${stripImports(wasiShim)}

${stripImports(cppLoader)}

const __WASM_GZ_B64 = "${wasmGz.toString("base64")}";

function __base64ToBytes(b64) {
  if (typeof Buffer !== "undefined") return new Uint8Array(Buffer.from(b64, "base64"));
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

async function __gunzip(bytes) {
  // DecompressionStream is universal across Node 18+, Workers, and modern
  // browsers (Chrome 80+, FF 113+, Safari 16.4+).
  const ds = new DecompressionStream("gzip");
  const stream = new Response(bytes).body.pipeThrough(ds);
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

// Each load() returns a fresh WebAssembly instance with its own linear
// memory. The earlier singleton-cache was wrong: any code that holds two
// CapnCpp instances (e.g., RPC client + server in the same process) needs
// independent scratch buffers, builders, and readers. Sharing a single
// instance silently broke as soon as two operations interleaved across an
// await boundary.
export async function load() {
  return await CapnCpp.load(await __gunzip(__base64ToBytes(__WASM_GZ_B64)));
}
`;

await mkdir(resolve(ROOT, "dist"), { recursive: true });
await writeFile(resolve(ROOT, "dist", "inlined.mjs"), bundle);

const raw = Buffer.byteLength(bundle, "utf8");
const gz = gzipSync(bundle, { level: 9 }).length;
console.log(`dist/inlined.mjs:  raw=${raw}  gzip=${gz}`);
