#!/usr/bin/env node
// Generates dist/inlined.mjs by concatenating cpp_loader.mjs +
// cpp_wasi_shim.mjs + the inlined wasm into one file. True single-file
// bundle: no relative imports inside dist/.
//
// tape_codec.mjs is intentionally NOT inlined. It's only needed by the
// optional capnwasm/tape entrypoint. Pulling it in here would bloat both
// inlined bundles by ~3 KB gzipped that nobody using `load()` directly
// needs. Users who want serialize/deserialize import them from
// `capnwasm/tape` separately, where bundlers can keep them out of
// browser bundles that don't reference them.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { gzipSync, brotliCompressSync, constants as zlibConstants } from "node:zlib";

const ROOT = resolve(new URL("..", import.meta.url).pathname);

const wasm        = await readFile(resolve(ROOT, "zig-out", "capnp_cpp.opt.wasm"));
const wasiShim    = await readFile(resolve(ROOT, "js", "cpp_wasi_runtime.mjs"), "utf8");
const cppLoader   = await readFile(resolve(ROOT, "js", "cpp_loader.mjs"), "utf8");

// Strip relative imports. We're inlining all the dependencies.
const stripImports = (src) =>
  src.replace(/^import\s+\{[^}]+\}\s+from\s+["']\.\/[^"']+["'];?\s*$/gm, "");

// Pre-brotli-compress the wasm before base64. Brotli compresses ~25%
// better than gzip on this wasm, which (since base64 of already-
// compressed bytes is incompressible by the outer gzip layer) translates
// directly into a ~9 KB smaller inlined.mjs gz.
//
// Runtime requirement: DecompressionStream("brotli") in:
//   - Node 18+
//   - Cloudflare Workers
//   - Chrome 124+ (Apr 2024)
//   - Firefox 126+ (May 2024)
//   - Safari 18+ (Sep 2024)
//
// This puts the default `import "capnwasm"` entry on a 2024 baseline.
// Older runtimes get a clear error pointing at `capnwasm/browser`,
// which is the universal-compatibility entry that loads the slim wasm
// via WebAssembly.instantiateStreaming on a separately-fetched .wasm
// (no embedded compression involved).
//
// Aligns with our existing 2024 baseline. Promise.withResolvers
// (Chrome 119/FF 121/Safari 17.4) is already used by the RPC layer
// with a runtime fallback.
const wasmBr = brotliCompressSync(wasm, {
  params: { [zlibConstants.BROTLI_PARAM_QUALITY]: 11 },
});

const bundle = `// capnwasm: single-file inlined bundle (cpp_loader + wasi shim + the
// wasm itself, brotli-compressed + base64-encoded). One import, one fetch.
//
// Runtime requirement: DecompressionStream("brotli"). Chrome 124+ /
// Firefox 126+ / Safari 18+ / Node 18+ / Cloudflare Workers. For older
// browsers, use \`capnwasm/browser\` (universal. Loads the slim wasm via
// WebAssembly.instantiateStreaming on a separately-fetched .wasm).
//
// Generated by js/build_inlined.mjs from cpp/build.sh. Do not edit by hand.

${stripImports(wasiShim)}

${stripImports(cppLoader)}

const __WASM_BR_B64 = "${wasmBr.toString("base64")}";

function __base64ToBytes(b64) {
  if (typeof Buffer !== "undefined") return new Uint8Array(Buffer.from(b64, "base64"));
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

async function __debrotli(bytes) {
  let ds;
  try {
    ds = new DecompressionStream("brotli");
  } catch (err) {
    if (typeof process !== "undefined" && process.versions?.node) {
      try {
        const zlib = await import("node:zlib");
        const decompressed = zlib.brotliDecompressSync(Buffer.from(bytes));
        return new Uint8Array(decompressed.buffer, decompressed.byteOffset, decompressed.byteLength);
      } catch (nodeErr) {
        throw new Error(
          "capnwasm: DecompressionStream(\\"brotli\\") and Node zlib brotli fallback both failed. " +
          "Original DecompressionStream error: " + err.message + "; Node fallback error: " + nodeErr.message
        );
      }
    }
    throw new Error(
      "capnwasm: DecompressionStream(\\"brotli\\") not available in this runtime. " +
      "The default \`import \\"capnwasm\\"\` entry needs Chrome 124+ / Firefox 126+ / " +
      "Safari 18+ / Node 18+ / Workers. For older browsers use \`import \\"capnwasm/browser\\"\` " +
      "+ \`import wasm from \\"capnwasm/capnp.slim.wasm\\"\`. Original error: " + err.message
    );
  }
  const stream = new Response(bytes).body.pipeThrough(ds);
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

// Each load() returns a fresh WebAssembly instance with its own linear
// memory. The earlier singleton-cache was wrong: any code that holds two
// CapnCpp instances (e.g., RPC client + server in the same process) needs
// independent scratch buffers, builders, and readers. Sharing a single
// instance silently broke as soon as two operations interleaved across an
// await boundary.
export async function load() {
  return await CapnCpp.load(await __debrotli(__base64ToBytes(__WASM_BR_B64)));
}
`;

await mkdir(resolve(ROOT, "dist"), { recursive: true });
await writeFile(resolve(ROOT, "dist", "inlined.mjs"), bundle);

const raw = Buffer.byteLength(bundle, "utf8");
const gz = gzipSync(bundle, { level: 9 }).length;
console.log(`dist/inlined.mjs:  raw=${raw}  gzip=${gz}`);
