#!/usr/bin/env node
// Generates dist/codegen.mjs. Single-file bundle of the capnp schema
// compiler wasm + its JS loader. Self-contained: no disk reads, no
// external imports. Mirrors build_inlined.mjs but for the compiler.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { gzipSync } from "node:zlib";

const ROOT = resolve(new URL("..", import.meta.url).pathname);

const wasm        = await readFile(resolve(ROOT, "zig-out", "capnpc.opt.wasm"));
const wasiRuntime = await readFile(resolve(ROOT, "js", "cpp_wasi_runtime.mjs"), "utf8");
const wasiShim    = await readFile(resolve(ROOT, "js", "cpp_wasi_shim.mjs"), "utf8");

// Pre-gzip the compiler wasm before base64-encoding. Same trick as
// inlined.mjs. Saves ~80 KB gz on the codegen bundle (the compiler wasm
// is ~715 KB raw / ~254 KB gzipped, so the base64 of the gzipped form is
// 4× shorter than base64 of raw).
const wasmGz = gzipSync(wasm, { level: 9 });

// Read the loader so we can inline the helper functions defined at module
// scope (typeToName, TYPE_WIDTHS, translateField, translateStruct). We
// only need the bottom half of the file. Everything from the helpers
// through the end. The class itself we re-emit standalone since its
// load() method differs (no disk read).
const loaderSrc = await readFile(resolve(ROOT, "js", "capnpc_loader.mjs"), "utf8");
const helpersIdx = loaderSrc.indexOf("// Map from Cap'n Proto schema type");
const HELPERS = helpersIdx >= 0 ? loaderSrc.slice(helpersIdx) : "";

const STRIP_NODE_IMPORTS = (s) =>
  s.replace(/^import\s+\{[^}]+\}\s+from\s+["']node:[^"']+["'];?\s*$/gm, "")
   .replace(/^import\s+\{[^}]+\}\s+from\s+["']\.\/[^"']+["'];?\s*$/gm, "");

// Drop a single re-export line. The shim re-exports `buildRuntimeWasiImports`
// for module-graph callers; once we inline the runtime alongside the shim,
// that re-export collides with the runtime's own `export function`.
const STRIP_REEXPORTS = (s, names) => {
  for (const n of names) {
    s = s.replace(new RegExp(`^export\\s+\\{\\s*${n}\\s*\\};?\\s*$`, "gm"), "");
  }
  return s;
};

const bundle = `// capnwasm/codegen: single-file bundle that ships the upstream Cap'n Proto
// schema COMPILER (cpp/vendor/capnp/compiler) statically linked through
// zig cc, base64-embedded, with its JS loader. Use this when you want to
// run schema codegen at runtime. Including in a browser, where there is
// no filesystem and no external 'capnp' binary. Standard schemas
// (c++.capnp, schema.capnp, etc.) are baked into the wasm so user
// imports of "/capnp/c++.capnp" resolve with zero host I/O.
//
// Generated by js/build_codegen_inlined.mjs. Do not edit by hand.

${STRIP_NODE_IMPORTS(wasiRuntime)}

${STRIP_REEXPORTS(STRIP_NODE_IMPORTS(wasiShim), ["buildRuntimeWasiImports"])}

const __CAPNPC_WASM_GZ_B64 = "${wasmGz.toString("base64")}";

function __base64ToBytes(b64) {
  if (typeof Buffer !== "undefined") return new Uint8Array(Buffer.from(b64, "base64"));
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

async function __gunzip(bytes) {
  // DecompressionStream("gzip") is universal: Node 18+, Workers, all
  // modern browsers (Chrome 80+, FF 113+, Safari 16.4+).
  const ds = new DecompressionStream("gzip");
  const stream = new Response(bytes).body.pipeThrough(ds);
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

const EMBEDDED_STANDARD_COUNT = 6;  // matches cpp/embed_standard_schemas.sh

export class CapnpCompiler {
  #instance;
  #memory;
  #exports;
  #u8() { return new Uint8Array(this.#memory.buffer); }
  #extraFiles = [];
  #addedThisCompile = 0;

  static async load() {
    const bytes = await __gunzip(__base64ToBytes(__CAPNPC_WASM_GZ_B64));
    const wasi = buildWasiImports();
    const { instance } = await WebAssembly.instantiate(bytes, {
      wasi_snapshot_preview1: wasi.imports,
    });
    wasi.setMemory(instance.exports.memory);
    const c = new CapnpCompiler();
    c.#instance = instance;
    c.#memory = instance.exports.memory;
    c.#exports = instance.exports;
    return c;
  }

  /** Register an extra schema resolvable by name during compile(). */
  addSchema(name, source) {
    const bytes = typeof source === "string" ? new TextEncoder().encode(source) : source;
    this.#extraFiles.push({ name, bytes });
  }

  #addFile(name, bytes) {
    const u8 = this.#u8();
    const inPtr = this.#exports.capnpc_in_ptr();
    const cap = this.#exports.capnpc_in_capacity();
    if (bytes.length > cap) throw new Error(\`schema source exceeds compiler scratch (\${cap} bytes)\`);
    u8.set(bytes, inPtr);
    const nameBytes = new TextEncoder().encode(name);
    if (bytes.length + nameBytes.length > cap) throw new Error("name + source exceeds scratch");
    u8.set(nameBytes, inPtr + bytes.length);
    if (this.#exports.capnpc_add_file(inPtr + bytes.length, nameBytes.length, bytes.length) !== 1) {
      throw new Error(\`capnpc_add_file(\${name}) failed\`);
    }
    this.#addedThisCompile++;
  }

  /**
   * Compile a single .capnp source. Returns the binary CodeGeneratorRequest
   * (Cap'n Proto framed message) as a Uint8Array, or throws with the
   * concatenated error text. Standard schemas are pre-loaded inside the
   * wasm itself; addSchema() lets you register more.
   */
  async compile(name, source) {
    const sourceBytes = typeof source === "string" ? new TextEncoder().encode(source) : source;
    this.#addedThisCompile = 0;
    this.#exports.capnpc_reset();
    for (const extra of this.#extraFiles) this.#addFile(extra.name, extra.bytes);
    this.#addFile(name, sourceBytes);
    const userIdx = EMBEDDED_STANDARD_COUNT + this.#extraFiles.length + this.#addedThisCompile - 1;
    const len = this.#exports.capnpc_compile(userIdx);
    if (len === 0) {
      const errLen = this.#exports.capnpc_get_errors();
      const u8 = this.#u8();
      const outPtr = this.#exports.capnpc_out_ptr();
      const errText = new TextDecoder().decode(u8.slice(outPtr, outPtr + errLen));
      throw new Error(\`capnp compile failed:\\n\${errText || "(no error text)"}\`);
    }
    const u8 = this.#u8();
    const outPtr = this.#exports.capnpc_out_ptr();
    return u8.slice(outPtr, outPtr + len);
  }

  /** One-shot compile + extract a struct model in our codegen-ready shape. */
  async compileToModel(name, source) {
    const requestBytes = await this.compile(name, source);
    const u8 = this.#u8();
    const inPtr = this.#exports.capnpc_in_ptr();
    new DataView(u8.buffer).setUint32(inPtr, requestBytes.length, true);
    u8.set(requestBytes, inPtr + 4);
    const len = this.#exports.capnpc_extract_structs();
    if (len === 0) throw new Error("capnpc_extract_structs failed");
    const outPtr = this.#exports.capnpc_out_ptr();
    const json = new TextDecoder().decode(u8.slice(outPtr, outPtr + len));
    const raw = JSON.parse(json);
    return raw.map(s => translateStruct(s, raw));
  }
}

${HELPERS}
`;

await mkdir(resolve(ROOT, "dist"), { recursive: true });
await writeFile(resolve(ROOT, "dist", "codegen.mjs"), bundle);

const raw = Buffer.byteLength(bundle, "utf8");
const gz  = gzipSync(bundle, { level: 9 }).length;
console.log(`dist/codegen.mjs:  raw=${raw}  gzip=${gz}`);
