#!/usr/bin/env node
// Generates dist/inlined.mjs by concatenating cpp_loader.mjs +
// cpp_wasi_shim.mjs + the inlined wasm into one file. True single-file
// bundle: no relative imports inside dist/.
//
// tape_codec.mjs is intentionally NOT inlined — it's only needed by the
// optional capnwasm/tape entrypoint. Pulling it in here would bloat both
// inlined bundles by ~3 KB gzipped that nobody using `load()` directly
// needs. Users who want serialize/deserialize import them from
// `capnwasm/tape` separately, where bundlers can keep them out of
// browser bundles that don't reference them.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { gzipSync } from "node:zlib";

const ROOT = resolve(new URL("..", import.meta.url).pathname);

const wasm        = await readFile(resolve(ROOT, "zig-out", "capnp_cpp.opt.wasm"));
const wasiShim    = await readFile(resolve(ROOT, "js", "cpp_wasi_runtime.mjs"), "utf8");
const cppLoader   = await readFile(resolve(ROOT, "js", "cpp_loader.mjs"), "utf8");

// Strip relative imports — we're inlining all the dependencies.
const stripImports = (src) =>
  src.replace(/^import\s+\{[^}]+\}\s+from\s+["']\.\/[^"']+["'];?\s*$/gm, "");

const bundle = `// capnwasm: single-file inlined bundle (cpp_loader + wasi shim + the
// wasm itself, base64-encoded). One import, one fetch.
//
// Generated by js/build_inlined.mjs from cpp/build.sh — do not edit by hand.

${stripImports(wasiShim)}

${stripImports(cppLoader)}

const __WASM_B64 = "${wasm.toString("base64")}";

function __base64ToBytes(b64) {
  if (typeof Buffer !== "undefined") return new Uint8Array(Buffer.from(b64, "base64"));
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

// Each load() returns a fresh WebAssembly instance with its own linear
// memory. The earlier singleton-cache was wrong: any code that holds two
// CapnCpp instances (e.g., RPC client + server in the same process) needs
// independent scratch buffers, builders, and readers. Sharing a single
// instance silently broke as soon as two operations interleaved across an
// await boundary.
export async function load() {
  return await CapnCpp.load(__base64ToBytes(__WASM_B64));
}
`;

// `--slim` writes dist/inlined.slim.mjs (the size-optimized opt-in build).
// Default is dist/inlined.mjs (the full-featured bundle every test imports
// and every existing `import "capnwasm"` user gets).
const isSlim = process.argv.includes("--slim");
const outName = isSlim ? "inlined.slim.mjs" : "inlined.mjs";

await mkdir(resolve(ROOT, "dist"), { recursive: true });
await writeFile(resolve(ROOT, "dist", outName), bundle);

const raw = Buffer.byteLength(bundle, "utf8");
const gz = gzipSync(bundle, { level: 9 }).length;
console.log(`dist/${outName}:  raw=${raw}  gzip=${gz}`);
