// JSON-shape ↔ capnp wire-bytes codec emitter.
//
// Closes the gap between capnwasm's typed builders/readers and the
// "give me a JSON tree, give me bytes back" pattern. For each top-level
// named struct in the manifest, emits an async pair:
//
//   import { ChatRequestToCapnp, ChatRequestFromCapnp } from "./codec.mjs";
//   const bytes = await ChatRequestToCapnp(openaiRequest);
//   const same  = await ChatRequestFromCapnp(bytes);
//
// The output module loads the capnwasm wasm runtime once (lazy + cached)
// and uses the dynamic builder/reader path for encode/decode. No
// schema-specific code is generated per struct — just one descriptor
// table per struct name.
//
// Source-format support:
//   • capnp source manifests: the manifest already carries struct
//     layouts (dataWords, ptrWords, bitOffsets, ptrIndexes), so we
//     translate directly.
//   • OpenAPI source manifests: no layouts in the manifest. The codec
//     emitter calls into emit-capnp to materialize a .capnp text, then
//     re-compiles it through the bundled wasm capnp compiler to get
//     the layouts, then emits the same codec shape.

const HEADER = `// Generated by \`npx capnwasm emit-codec\`. Do not edit by hand.
//
// Usage:
//   import { <Name>ToCapnp, <Name>FromCapnp } from "./codec.mjs";
//   const bytes = await <Name>ToCapnp(jsObject);   // → Uint8Array
//   const obj   = await <Name>FromCapnp(bytes);    // → plain JS object
`;

/**
 * Build the codec module text from a manifest.
 *
 * Returns { text, summary } where summary lists which structs got
 * codecs and which were skipped (and why).
 *
 * @param {object} manifest
 * @param {object} [opts]
 * @param {string} [opts.runtimeImport="capnwasm"]  capnp runtime import
 * @param {string} [opts.dynamicImport="capnwasm/dynamic"]
 * @param {Array<object>} [opts.structs]  pre-resolved layout-bearing
 *        structs (used by the CLI when it had to compile the .capnp
 *        text from an OpenAPI source first to get layouts).
 */
export function buildCodec(manifest, opts = {}) {
  const runtimeImport = opts.runtimeImport ?? "capnwasm";
  const dynamicImport = opts.dynamicImport ?? "capnwasm/dynamic";
  const structs = opts.structs ?? manifest.structs ?? [];

  const skipped = [];
  const emitted = [];

  const lines = [];
  lines.push(HEADER);
  lines.push(``);
  lines.push(`import { load } from ${JSON.stringify(runtimeImport)};`);
  lines.push(`import { defineSchema, encodeDynamic, openDynamic } from ${JSON.stringify(dynamicImport)};`);
  lines.push(``);
  lines.push(`let _cppPromise = null;`);
  lines.push(`function _cpp() { return (_cppPromise ??= load()); }`);
  lines.push(``);

  // Build a lookup so nested struct references can be resolved into
  // inline schema descriptors. Cycles are guarded by tracking the
  // resolution stack and bottoming out at AnyPointer when a cycle is
  // detected.
  const structIndex = new Map(structs.map((s) => [s.name, s]));

  for (const s of structs) {
    if (!hasLayout(s)) {
      skipped.push({ name: s.name, reason: "no wire layout (run emit-capnp + capnp compile first)" });
      continue;
    }
    const { spec, ok, reason } = structToSchemaSpec(s, structIndex, new Set([s.name]));
    if (!ok) {
      skipped.push({ name: s.name, reason });
      continue;
    }
    const ident = jsIdent(s.name);
    lines.push(`const _SCHEMA_${ident.toUpperCase()} = defineSchema(${stringifySpec(spec)}, { dataWords: ${s.dataWords ?? 0}, ptrWords: ${s.ptrWords ?? 0} });`);
    lines.push(``);
    lines.push(`/** ${s.name} → capnp wire bytes. */`);
    lines.push(`export async function ${ident}ToCapnp(obj) {`);
    lines.push(`  return encodeDynamic(await _cpp(), _SCHEMA_${ident.toUpperCase()}, obj);`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`/** capnp wire bytes → ${s.name} JS object. */`);
    lines.push(`export async function ${ident}FromCapnp(bytes) {`);
    lines.push(`  return openDynamic(await _cpp(), _SCHEMA_${ident.toUpperCase()}, bytes).toObject();`);
    lines.push(`}`);
    lines.push(``);
    emitted.push(s.name);
  }

  if (emitted.length === 0) {
    lines.push(`// (no codecs emitted: no structs in the manifest had wire layouts)`);
  }
  return {
    text: lines.join("\n"),
    summary: { emitted, skipped },
  };
}

// --- Helpers ---------------------------------------------------------

function hasLayout(s) {
  // A struct has wire layout if dataWords / ptrWords are present and
  // every field has either a bitOffset (data) or a ptrIndex (pointer).
  if (typeof s.dataWords !== "number" || typeof s.ptrWords !== "number") return false;
  for (const f of s.fields ?? []) {
    if (f.kind === "data" && typeof f.bitOffset !== "number") return false;
    if (f.kind === "pointer" && typeof f.ptrIndex !== "number") return false;
  }
  return true;
}

function structToSchemaSpec(s, structIndex, stack) {
  const spec = {};
  for (const f of s.fields ?? []) {
    const desc = fieldToDescriptor(f, structIndex, stack);
    if (!desc.ok) return { ok: false, reason: `field ${f.name}: ${desc.reason}` };
    spec[f.name] = desc.value;
  }
  return { ok: true, spec };
}

function fieldToDescriptor(f, structIndex, stack) {
  const t = f.type;
  if (!t) return { ok: false, reason: "missing type" };

  // List(...) types.
  const lm = t.match(/^List\(([^)]+)\)$/);
  if (lm) {
    const inner = lm[1];
    if (LIST_PRIM_KIND[inner]) return { ok: true, value: { kind: LIST_PRIM_KIND[inner], slot: f.ptrIndex } };
    if (inner === "Text") return { ok: true, value: { kind: "listText", slot: f.ptrIndex } };
    if (inner === "Data") return { ok: true, value: { kind: "listData", slot: f.ptrIndex } };
    // List<Struct>: resolve the element struct from the index.
    const elem = structIndex?.get(inner);
    if (!elem) return { ok: false, reason: `List<${inner}> element struct not in manifest` };
    if (stack?.has(inner)) {
      // Cycle: bottom out as a list of AnyPointer so encode/decode
      // doesn't recurse forever.
      return { ok: true, value: { kind: "listStruct", slot: f.ptrIndex, element: { fields: {}, dataWords: 0, ptrWords: 0 } } };
    }
    if (!hasLayout(elem)) return { ok: false, reason: `List<${inner}> element struct lacks wire layout` };
    const sub = structToSchemaSpec(elem, structIndex, new Set([...(stack ?? []), inner]));
    if (!sub.ok) return { ok: false, reason: `List<${inner}>: ${sub.reason}` };
    return {
      ok: true,
      value: {
        kind: "listStruct",
        slot: f.ptrIndex,
        element: { fields: sub.spec, dataWords: elem.dataWords ?? 0, ptrWords: elem.ptrWords ?? 0 },
      },
    };
  }

  if (t === "Bool")    return { ok: true, value: { kind: "bool",  bitOffset: f.bitOffset ?? 0 } };
  if (t === "Text")    return { ok: true, value: { kind: "text",  slot: f.ptrIndex } };
  if (t === "Data")    return { ok: true, value: { kind: "data",  slot: f.ptrIndex } };
  if (t === "Void")    return { ok: true, value: { kind: "void" } };
  if (t === "AnyPointer") return { ok: true, value: { kind: "anyPointer", slot: f.ptrIndex } };

  if (PRIMITIVE_KIND[t]) {
    return { ok: true, value: { kind: PRIMITIVE_KIND[t], offset: (f.bitOffset ?? 0) >>> 3 } };
  }

  // Nested struct ref: resolve from the index, recursing into its fields.
  const nested = structIndex?.get(t);
  if (nested) {
    if (stack?.has(t)) {
      return { ok: true, value: { kind: "anyPointer", slot: f.ptrIndex } };
    }
    if (!hasLayout(nested)) return { ok: false, reason: `${t} lacks wire layout` };
    const sub = structToSchemaSpec(nested, structIndex, new Set([...(stack ?? []), t]));
    if (!sub.ok) return { ok: false, reason: `${t}: ${sub.reason}` };
    return {
      ok: true,
      value: {
        kind: "struct",
        slot: f.ptrIndex,
        schema: { fields: sub.spec, dataWords: nested.dataWords ?? 0, ptrWords: nested.ptrWords ?? 0 },
      },
    };
  }

  return { ok: false, reason: `unknown type ${t}` };
}

function jsIdent(s) {
  // Sanitize struct name for use as a JS identifier. Capnp PascalCase
  // names are usually JS-safe; this just guards against the few that
  // aren't.
  let n = String(s).replace(/[^A-Za-z0-9_$]/g, "_");
  if (/^[0-9]/.test(n)) n = "_" + n;
  return n || "Anon";
}

function stringifySpec(spec) {
  // Pretty-print a schema spec object inline. Keep keys unquoted for
  // readability when they're valid JS identifiers.
  const entries = Object.entries(spec).map(([k, v]) => {
    const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
    return `  ${key}: ${stringifyDesc(v)}`;
  });
  return `{\n${entries.join(",\n")}\n}`;
}

function stringifyDesc(desc) {
  // Most descriptors are flat (kind/slot/offset/bitOffset). Nested
  // struct / listStruct descriptors carry a `schema` or `element`
  // sub-spec that needs deeper formatting.
  const parts = [];
  for (const [k, v] of Object.entries(desc)) {
    if ((k === "schema" || k === "element") && v && typeof v === "object") {
      parts.push(`${k}: ${stringifyNestedSchema(v)}`);
    } else {
      parts.push(`${k}: ${JSON.stringify(v)}`);
    }
  }
  return `{ ${parts.join(", ")} }`;
}

function stringifyNestedSchema(schema) {
  // The dynamic builder/reader expects `element` (for listStruct) and
  // `schema` (for struct) to be the OUTPUT of defineSchema, not a raw
  // spec. Emit an inline `defineSchema(...)` call so the nested
  // descriptor is fully constructed at module load.
  return `defineSchema(${stringifySpec(schema.fields ?? {})}, { dataWords: ${schema.dataWords ?? 0}, ptrWords: ${schema.ptrWords ?? 0} })`;
}

const PRIMITIVE_KIND = {
  UInt8:   "uint8",
  UInt16:  "uint16",
  UInt32:  "uint32",
  UInt64:  "uint64",
  Int8:    "int8",
  Int16:   "int16",
  Int32:   "int32",
  Int64:   "int64",
  Float32: "float32",
  Float64: "float64",
};

const LIST_PRIM_KIND = {
  Bool:    "listBool",
  UInt8:   "listUint8",  UInt16: "listUint16",  UInt32: "listUint32",  UInt64: "listUint64",
  Int8:    "listInt8",   Int16:  "listInt16",   Int32:  "listInt32",   Int64:  "listInt64",
  Float32: "listFloat32", Float64: "listFloat64",
};
