// Contract test harness emitter.
//
// Reads a manifest produced by `npx capnwasm manifest` and emits a Node
// `--test`-compatible test file that exercises every operation against
// a configurable target.
//
// Capnp RPC operations:
//   default target is an in-process mock server (paired-memory transport
//   with default-response handlers built from the manifest), so the
//   harness is runnable with zero infrastructure. Override with
//     CAPNWASM_HARNESS_TARGET=ws://staging.example.com/rpc
//   to point at a real endpoint instead.
//
// REST operations:
//   the harness generates fetch-based tests that need a real base URL
//   (a generic mock REST server can't be synthesized from a manifest
//   because OpenAPI/@rest don't pin response bodies — they declare
//   shapes, not values, and arbitrary handler logic is out of scope for
//   a manifest). Set
//     CAPNWASM_HARNESS_REST_TARGET=https://staging.example.com
//   to run them; without it they skip with a message naming the var.
//
// Why generate a file rather than run the tests directly: the emitted
// file is a real test fixture that the consuming app commits and runs
// from its own CI. That keeps the contract surface visible in the
// app's test output (and PR diffs when the schema changes), instead of
// being hidden inside a tooling subprocess.

const HARNESS_HEADER = `// Contract test harness — generated by \`npx capnwasm harness\` from a
// schema manifest. Do not edit by hand. Re-run the command to refresh
// after the schema changes.
//
// Capnp targets — default is in-process mock; override with:
//   CAPNWASM_HARNESS_TARGET=ws://host/rpc node --test path/to/this.mjs
//
// REST targets — needs a real base URL:
//   CAPNWASM_HARNESS_REST_TARGET=https://staging.example.com node --test ...
//
// Asserts only that each operation is callable and that its response
// decodes against the declared result schema. Business semantics
// belong in your app's own tests.
`;

/**
 * Build a contract test harness for a manifest.
 *
 * @param {object} manifest - the parsed manifest JSON
 * @param {object} opts
 * @param {string} opts.genImport - import specifier for the generated
 *        codegen module (e.g., "./user.gen.mjs"). Must export the
 *        per-struct {Name}Builder / {Name}Reader and the per-API
 *        create{Name}Client factory.
 * @param {string} [opts.runtimeImport="capnwasm"] - import specifier for
 *        the capnp runtime entry ({load}). For npm consumers the default
 *        "capnwasm" is right; for in-tree use pass an explicit path
 *        (e.g. "../dist/inlined.mjs").
 * @param {string} [opts.rpcImport="<runtimeImport>/rpc"] - import
 *        specifier for the RPC layer ({RpcSession, InterfaceRegistry,
 *        createMemoryTransportPair, connectWebSocket}). Defaults to the
 *        "/rpc" subpath of runtimeImport, which is the npm package's
 *        published export. Override when runtimeImport is an absolute
 *        file path that has no "/rpc" subpath (e.g. when pointing at a
 *        single bundled file or a sibling source module).
 * @returns {string} the test file source
 */
export function buildHarness(manifest, opts) {
  if (!opts?.genImport) {
    throw new Error("buildHarness: opts.genImport is required");
  }
  const runtimeImport = opts.runtimeImport ?? "capnwasm";
  const rpcImport     = opts.rpcImport ?? (runtimeImport + "/rpc");

  const hasCapnp = (manifest.interfaces ?? []).length > 0;
  const hasRest  = (manifest.restApis  ?? []).length > 0;

  const lines = [];
  lines.push(HARNESS_HEADER);
  lines.push(``);
  lines.push(`import { test, before, after } from "node:test";`);
  lines.push(`import { strict as assert } from "node:assert";`);
  if (hasCapnp) {
    lines.push(`import { load } from ${JSON.stringify(runtimeImport)};`);
    lines.push(`import {`);
    lines.push(`  RpcSession,`);
    lines.push(`  InterfaceRegistry,`);
    lines.push(`  createMemoryTransportPair,`);
    lines.push(`  connectWebSocket,`);
    lines.push(`} from ${JSON.stringify(rpcImport)};`);
  }
  lines.push(`import * as gen from ${JSON.stringify(opts.genImport)};`);
  lines.push(``);

  if (hasCapnp) emitCapnpHarness(lines, manifest);
  if (hasRest)  emitRestHarness(lines, manifest);

  return lines.join("\n");
}

function emitCapnpHarness(lines, manifest) {
  lines.push(`// ---- capnp RPC contract tests ----`);
  lines.push(`const CAPNP_TARGET = process.env.CAPNWASM_HARNESS_TARGET ?? "memory";`);
  lines.push(``);
  lines.push(`let cppClient, cppServer, sessionClient, sessionServer, root;`);
  lines.push(``);
  lines.push(`before(async () => {`);
  lines.push(`  cppClient = await load();`);
  lines.push(`  if (CAPNP_TARGET === "memory") {`);
  lines.push(`    cppServer = await load();`);
  lines.push(`    const { a, b } = createMemoryTransportPair();`);
  lines.push(`    const reg = new InterfaceRegistry();`);
  lines.push(`    // Default-response handlers: each method returns an empty`);
  lines.push(`    // builder, leaving every result field at its capnp default.`);
  lines.push(`    // The contract is "request encodes, response decodes" — your`);
  lines.push(`    // app's own tests assert business meaning.`);

  const structByName = new Map((manifest.structs ?? []).map((s) => [s.name, s]));
  const tests = [];
  for (const iface of manifest.interfaces ?? []) {
    const ifaceIdLiteral = bigintLiteral(iface.id);
    for (const m of iface.methods ?? []) {
      lines.push(`    reg.register(${ifaceIdLiteral}, ${m.ordinal}, (_t, ctx) => {`);
      lines.push(`      ctx.beginResults(gen.${m.resultsStruct}Builder);`);
      lines.push(`    });`);
      tests.push({
        ifaceId: ifaceIdLiteral,
        ordinal: m.ordinal,
        operationId: m.operationId,
        paramsName: m.paramsStruct,
        resultsName: m.resultsStruct,
        paramsStruct: structByName.get(m.paramsStruct),
        resultsStruct: structByName.get(m.resultsStruct),
      });
    }
  }

  lines.push(`    sessionServer = new RpcSession(cppServer, b, reg, { bootstrap: {} });`);
  lines.push(`    sessionClient = new RpcSession(cppClient, a);`);
  lines.push(`  } else if (CAPNP_TARGET.startsWith("ws")) {`);
  lines.push(`    sessionClient = await connectWebSocket(cppClient, CAPNP_TARGET);`);
  lines.push(`  } else {`);
  lines.push(`    throw new Error("unsupported CAPNWASM_HARNESS_TARGET: " + CAPNP_TARGET);`);
  lines.push(`  }`);
  lines.push(`  root = sessionClient.bootstrap();`);
  lines.push(`});`);
  lines.push(``);
  lines.push(`after(() => {`);
  lines.push(`  try { sessionClient?.close(); } catch {}`);
  lines.push(`  try { sessionServer?.close(); } catch {}`);
  lines.push(`});`);
  lines.push(``);

  for (const t of tests) {
    lines.push(`test(${JSON.stringify(t.operationId + ": call returns a parseable response")}, async () => {`);
    lines.push(`  const r = root.callBuilder(${t.ifaceId}, ${t.ordinal}, gen.${t.paramsName}Builder);`);
    if (t.paramsStruct) {
      for (const f of t.paramsStruct.fields ?? []) {
        const setter = defaultSetterForField(f);
        if (setter !== null) {
          lines.push(`  r.params.${f.name} = ${setter};`);
        }
      }
    }
    lines.push(`  const result = await r.send({`);
    lines.push(`    resultsReader: gen.${t.resultsName}Reader,`);
    lines.push(`    extract: (rdr) => {`);
    lines.push(`      // Touch every result field so the call exercises the`);
    lines.push(`      // declared shape end-to-end. List<Struct> fields land`);
    lines.push(`      // here as the wrapper object — accessing it materializes`);
    lines.push(`      // length + per-element accessors and is sufficient for`);
    lines.push(`      // the "field is decodable" contract.`);
    lines.push(`      const out = {};`);
    if (t.resultsStruct) {
      for (const f of t.resultsStruct.fields ?? []) {
        lines.push(`      out.${f.name} = rdr.${f.name};`);
      }
    }
    lines.push(`      return out;`);
    lines.push(`    },`);
    lines.push(`  }).promise;`);
    lines.push(`  assert.ok(result !== undefined, ${JSON.stringify(t.operationId + ": result was undefined")});`);
    lines.push(`});`);
    lines.push(``);
  }
}

function emitRestHarness(lines, manifest) {
  lines.push(`// ---- REST contract tests ----`);
  lines.push(`// REST contract assertions need a real base URL — set`);
  lines.push(`// CAPNWASM_HARNESS_REST_TARGET=https://staging.example.com to run.`);
  lines.push(`const REST_TARGET = process.env.CAPNWASM_HARNESS_REST_TARGET;`);
  lines.push(``);

  for (const api of manifest.restApis ?? []) {
    const factoryName = `create${api.name}Client`;
    for (const m of api.methods ?? []) {
      const args = (m.params ?? []).map((p) => synthesizeRestParamLiteral(p, manifest));
      const argList = args.join(", ");
      const skipMsg = `${m.operationId}: set CAPNWASM_HARNESS_REST_TARGET to run`;
      lines.push(`test(${JSON.stringify(m.operationId + ": " + m.httpMethod + " " + m.path)}, async (t) => {`);
      lines.push(`  if (!REST_TARGET) { t.skip(${JSON.stringify(skipMsg)}); return; }`);
      lines.push(`  const client = gen.${factoryName}({ baseUrl: REST_TARGET });`);
      lines.push(`  const result = await client.${m.name}(${argList});`);
      lines.push(`  // For async-iterable / paginated methods, drain the first`);
      lines.push(`  // page so we exercise the response decode without committing`);
      lines.push(`  // to walking arbitrarily large pagination histories.`);
      if (m.isAsyncIterable) {
        lines.push(`  for await (const _item of result) break;`);
      } else {
        lines.push(`  assert.ok(result !== undefined, ${JSON.stringify(m.operationId + ": result was undefined")});`);
      }
      lines.push(`});`);
      lines.push(``);
    }
  }
}

/**
 * For a capnp field manifest descriptor, return a JS expression string
 * for an appropriate default value to set via the codegen builder.
 * Returns `null` for field types where the codegen builder has no
 * setter (List<Struct>, nested struct refs) — those are left at their
 * capnp defaults (null pointer / empty list), which is the correct
 * wire behaviour and what the mock handler responds with.
 */
function defaultSetterForField(field) {
  const t = field.type;
  if (!t) return null;
  const listMatch = t.match(/^List\(([^)]+)\)$/);
  if (listMatch) {
    const inner = listMatch[1];
    if (PRIMITIVE_DEFAULTS[inner] !== undefined || inner === "Text" || inner === "Data") {
      return "[]";
    }
    return null;  // List(Struct), List(List(...)) — left as null pointer
  }
  if (/^[A-Z]/.test(t) && PRIMITIVE_DEFAULTS[t] === undefined) {
    return null;  // nested struct ref — left as null pointer
  }
  return PRIMITIVE_DEFAULTS[t] ?? null;
}

const PRIMITIVE_DEFAULTS = {
  Bool:    "false",
  UInt8:   "0",
  UInt16:  "0",
  UInt32:  "0",
  UInt64:  "0n",
  Int8:    "0",
  Int16:   "0",
  Int32:   "0",
  Int64:   "0n",
  Float32: "0",
  Float64: "0",
  Text:    `""`,
  Data:    "new Uint8Array(0)",
  Void:    "undefined",
};

/**
 * Synthesize a JS literal for a REST method parameter. Path params get
 * a stable contract-fixture identifier ("contract-test") so generated
 * URLs are syntactically valid; query/header/body params get the
 * type's zero value (mirrors the capnp default-response choice). Object
 * body types land as `{}` so the generated client's serializer can
 * still produce a well-formed request body.
 */
function synthesizeRestParamLiteral(param, _manifest) {
  const t = (param.type ?? "string").toLowerCase();
  if (t === "string") return param.in === "path" ? `"contract-test"` : `""`;
  if (t === "boolean" || t === "bool") return "false";
  if (t === "number" || t === "integer" || t === "int") return "0";
  if (t === "bigint") return "0n";
  if (t === "uint8array") return "new Uint8Array(0)";
  return "{}";
}

/**
 * Render a 64-bit interface id as a BigInt literal expression suitable
 * for source generation.
 */
function bigintLiteral(id) {
  if (typeof id === "bigint") return `0x${id.toString(16)}n`;
  if (typeof id !== "string") return `BigInt(${JSON.stringify(String(id))})`;
  if (id.startsWith("0x") || id.startsWith("0X")) return `${id}n`;
  try { return `0x${BigInt(id).toString(16)}n`; }
  catch { return `BigInt(${JSON.stringify(id)})`; }
}
