// Single-file entry point: the wasm is inlined as base64 so importing this
// module needs zero extra fetches. Larger JS bundle, no second network trip.
//
// Use this if you can't or don't want to ship a separate .wasm asset.
// For best caching/parallel-load behaviour, prefer the default export
// from "capnwasm" which fetches the wasm separately.
//
// Generated by `bash cpp/build.sh` (which runs js/build_inlined.mjs).

import { CapnCpp } from "./cpp_loader.mjs";

// __WASM_BASE64__ is replaced at build time by js/build_inlined.mjs.
const WASM_B64 = "__WASM_BASE64__";

function base64ToBytes(b64) {
  if (typeof Buffer !== "undefined") return new Uint8Array(Buffer.from(b64, "base64"));
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

let cached = null;

/** Load capnwasm with the wasm baked in. Resolves to a CapnCpp instance. */
export async function load() {
  if (cached) return cached;
  cached = await CapnCpp.load(base64ToBytes(WASM_B64));
  return cached;
}

export { CapnCpp };
