#!/bin/bash
# Generates cpp/standard_schemas.h — a header containing the standard
# capnp schemas as static char arrays so the compiler wasm can serve
# imports of /capnp/c++.capnp etc. without host filesystem access.
# Re-run whenever the vendored .capnp files change.

set -e
cd "$(dirname "$0")/.."

OUT=cpp/standard_schemas.h

cat > "$OUT" <<'HDR'
// AUTO-GENERATED by cpp/embed_standard_schemas.sh — do not edit by hand.
// Standard capnp schemas embedded as char arrays so the wasm-built compiler
// can resolve imports of /capnp/c++.capnp etc. with zero host I/O.
#pragma once
#include <stddef.h>

struct EmbeddedSchema {
  const char* name;
  const char* content;
  size_t len;
};

HDR

SCHEMAS=(
  "capnp/c++.capnp"
  "capnp/schema.capnp"
  "capnp/stream.capnp"
  "capnp/rpc.capnp"
  "capnp/rpc-twoparty.capnp"
  "capnp/persistent.capnp"
)

# Emit each schema as `static const char SCHEMA_<n>[] = R"...(...)";`
i=0
for s in "${SCHEMAS[@]}"; do
  src="cpp/vendor/$s"
  if [ ! -f "$src" ]; then
    echo "warn: missing $src — skipping" >&2
    continue
  fi
  # C++ raw string with a custom delimiter unlikely to appear in capnp source.
  echo "static const char STD_SCHEMA_${i}[] = R\"CWEMBED(" >> "$OUT"
  cat "$src" >> "$OUT"
  echo ")CWEMBED\";" >> "$OUT"
  i=$((i+1))
done

cat >> "$OUT" <<HDR

// Table of name → content. The compiler iterates this once at startup
// and pre-loads each into the virtual file table.
static const EmbeddedSchema STANDARD_SCHEMAS[] = {
HDR

i=0
for s in "${SCHEMAS[@]}"; do
  src="cpp/vendor/$s"
  if [ ! -f "$src" ]; then continue; fi
  echo "  { \"$s\", STD_SCHEMA_${i}, sizeof(STD_SCHEMA_${i}) - 1 }," >> "$OUT"
  i=$((i+1))
done

cat >> "$OUT" <<HDR
};
static const size_t STANDARD_SCHEMA_COUNT = sizeof(STANDARD_SCHEMAS) / sizeof(STANDARD_SCHEMAS[0]);
HDR

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
