// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: schema.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 2000000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(8e6fb1b984430e89);
CAPNP_DECLARE_SCHEMA(c4de4f0af3b7d7ce);
CAPNP_DECLARE_SCHEMA(f403879876925bc9);
CAPNP_DECLARE_SCHEMA(f1917f5bc205a55a);
CAPNP_DECLARE_SCHEMA(fbf2dcb76784515d);
CAPNP_DECLARE_SCHEMA(941e8bfa68bda6c3);
CAPNP_DECLARE_SCHEMA(bd3089881cf633d4);

}  // namespace schemas
}  // namespace capnp


struct Expression {
  Expression() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    NULL_VAL,
    BOOL_FALSE,
    BOOL_TRUE,
    INT_VAL,
    FLOAT_VAL,
    TEXT,
    DATA,
    ARRAY,
    OBJECT,
    IMPORT_REF,
    EXPORT_REF,
    PIPELINE,
    ERROR_VAL,
    DATE,
    BIGINT,
    UNDEFINED_VAL,
  };

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(8e6fb1b984430e89, 2, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct KeyValue {
  KeyValue() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(c4de4f0af3b7d7ce, 0, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct PipelineExpr {
  PipelineExpr() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f403879876925bc9, 0, 3)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct ErrorVal {
  ErrorVal() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f1917f5bc205a55a, 0, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Message {
  Message() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    PUSH,
    PULL,
    RESOLVE,
    REJECT,
    RELEASE,
    STREAM,
    ABORT,
    PIPE,
  };

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(fbf2dcb76784515d, 2, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct ResolveReject {
  ResolveReject() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(941e8bfa68bda6c3, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Release {
  Release() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(bd3089881cf633d4, 2, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class Expression::Reader {
public:
  typedef Expression Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isNullVal() const;
  inline  ::capnp::Void getNullVal() const;

  inline bool isBoolFalse() const;
  inline  ::capnp::Void getBoolFalse() const;

  inline bool isBoolTrue() const;
  inline  ::capnp::Void getBoolTrue() const;

  inline bool isIntVal() const;
  inline  ::int64_t getIntVal() const;

  inline bool isFloatVal() const;
  inline double getFloatVal() const;

  inline bool isText() const;
  inline bool hasText() const;
  inline  ::capnp::Text::Reader getText() const;

  inline bool isData() const;
  inline bool hasData() const;
  inline  ::capnp::Data::Reader getData() const;

  inline bool isArray() const;
  inline bool hasArray() const;
  inline  ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>::Reader getArray() const;

  inline bool isObject() const;
  inline bool hasObject() const;
  inline  ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>::Reader getObject() const;

  inline bool isImportRef() const;
  inline  ::int64_t getImportRef() const;

  inline bool isExportRef() const;
  inline  ::int64_t getExportRef() const;

  inline bool isPipeline() const;
  inline bool hasPipeline() const;
  inline  ::PipelineExpr::Reader getPipeline() const;

  inline bool isErrorVal() const;
  inline bool hasErrorVal() const;
  inline  ::ErrorVal::Reader getErrorVal() const;

  inline bool isDate() const;
  inline double getDate() const;

  inline bool isBigint() const;
  inline bool hasBigint() const;
  inline  ::capnp::Text::Reader getBigint() const;

  inline bool isUndefinedVal() const;
  inline  ::capnp::Void getUndefinedVal() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Expression::Builder {
public:
  typedef Expression Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isNullVal();
  inline  ::capnp::Void getNullVal();
  inline void setNullVal( ::capnp::Void value = ::capnp::VOID);

  inline bool isBoolFalse();
  inline  ::capnp::Void getBoolFalse();
  inline void setBoolFalse( ::capnp::Void value = ::capnp::VOID);

  inline bool isBoolTrue();
  inline  ::capnp::Void getBoolTrue();
  inline void setBoolTrue( ::capnp::Void value = ::capnp::VOID);

  inline bool isIntVal();
  inline  ::int64_t getIntVal();
  inline void setIntVal( ::int64_t value);

  inline bool isFloatVal();
  inline double getFloatVal();
  inline void setFloatVal(double value);

  inline bool isText();
  inline bool hasText();
  inline  ::capnp::Text::Builder getText();
  inline void setText( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initText(unsigned int size);
  inline void adoptText(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownText();

  inline bool isData();
  inline bool hasData();
  inline  ::capnp::Data::Builder getData();
  inline void setData( ::capnp::Data::Reader value);
  inline  ::capnp::Data::Builder initData(unsigned int size);
  inline void adoptData(::capnp::Orphan< ::capnp::Data>&& value);
  inline ::capnp::Orphan< ::capnp::Data> disownData();

  inline bool isArray();
  inline bool hasArray();
  inline  ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>::Builder getArray();
  inline void setArray( ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>::Builder initArray(unsigned int size);
  inline void adoptArray(::capnp::Orphan< ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>> disownArray();

  inline bool isObject();
  inline bool hasObject();
  inline  ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>::Builder getObject();
  inline void setObject( ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>::Builder initObject(unsigned int size);
  inline void adoptObject(::capnp::Orphan< ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>> disownObject();

  inline bool isImportRef();
  inline  ::int64_t getImportRef();
  inline void setImportRef( ::int64_t value);

  inline bool isExportRef();
  inline  ::int64_t getExportRef();
  inline void setExportRef( ::int64_t value);

  inline bool isPipeline();
  inline bool hasPipeline();
  inline  ::PipelineExpr::Builder getPipeline();
  inline void setPipeline( ::PipelineExpr::Reader value);
  inline  ::PipelineExpr::Builder initPipeline();
  inline void adoptPipeline(::capnp::Orphan< ::PipelineExpr>&& value);
  inline ::capnp::Orphan< ::PipelineExpr> disownPipeline();

  inline bool isErrorVal();
  inline bool hasErrorVal();
  inline  ::ErrorVal::Builder getErrorVal();
  inline void setErrorVal( ::ErrorVal::Reader value);
  inline  ::ErrorVal::Builder initErrorVal();
  inline void adoptErrorVal(::capnp::Orphan< ::ErrorVal>&& value);
  inline ::capnp::Orphan< ::ErrorVal> disownErrorVal();

  inline bool isDate();
  inline double getDate();
  inline void setDate(double value);

  inline bool isBigint();
  inline bool hasBigint();
  inline  ::capnp::Text::Builder getBigint();
  inline void setBigint( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initBigint(unsigned int size);
  inline void adoptBigint(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownBigint();

  inline bool isUndefinedVal();
  inline  ::capnp::Void getUndefinedVal();
  inline void setUndefinedVal( ::capnp::Void value = ::capnp::VOID);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Expression::Pipeline {
public:
  typedef Expression Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class KeyValue::Reader {
public:
  typedef KeyValue Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasKey() const;
  inline  ::capnp::Text::Reader getKey() const;

  inline bool hasValue() const;
  inline  ::Expression::Reader getValue() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class KeyValue::Builder {
public:
  typedef KeyValue Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasKey();
  inline  ::capnp::Text::Builder getKey();
  inline void setKey( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initKey(unsigned int size);
  inline void adoptKey(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownKey();

  inline bool hasValue();
  inline  ::Expression::Builder getValue();
  inline void setValue( ::Expression::Reader value);
  inline  ::Expression::Builder initValue();
  inline void adoptValue(::capnp::Orphan< ::Expression>&& value);
  inline ::capnp::Orphan< ::Expression> disownValue();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class KeyValue::Pipeline {
public:
  typedef KeyValue Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::Expression::Pipeline getValue();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class PipelineExpr::Reader {
public:
  typedef PipelineExpr Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasSource() const;
  inline  ::Expression::Reader getSource() const;

  inline bool hasPath() const;
  inline  ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>::Reader getPath() const;

  inline bool hasArgs() const;
  inline  ::Expression::Reader getArgs() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class PipelineExpr::Builder {
public:
  typedef PipelineExpr Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSource();
  inline  ::Expression::Builder getSource();
  inline void setSource( ::Expression::Reader value);
  inline  ::Expression::Builder initSource();
  inline void adoptSource(::capnp::Orphan< ::Expression>&& value);
  inline ::capnp::Orphan< ::Expression> disownSource();

  inline bool hasPath();
  inline  ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>::Builder getPath();
  inline void setPath( ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>::Reader value);
  inline void setPath(::kj::ArrayPtr<const  ::capnp::Text::Reader> value);
  inline  ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>::Builder initPath(unsigned int size);
  inline void adoptPath(::capnp::Orphan< ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>> disownPath();

  inline bool hasArgs();
  inline  ::Expression::Builder getArgs();
  inline void setArgs( ::Expression::Reader value);
  inline  ::Expression::Builder initArgs();
  inline void adoptArgs(::capnp::Orphan< ::Expression>&& value);
  inline ::capnp::Orphan< ::Expression> disownArgs();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class PipelineExpr::Pipeline {
public:
  typedef PipelineExpr Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::Expression::Pipeline getSource();
  inline  ::Expression::Pipeline getArgs();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class ErrorVal::Reader {
public:
  typedef ErrorVal Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasType() const;
  inline  ::capnp::Text::Reader getType() const;

  inline bool hasMessage() const;
  inline  ::capnp::Text::Reader getMessage() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ErrorVal::Builder {
public:
  typedef ErrorVal Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasType();
  inline  ::capnp::Text::Builder getType();
  inline void setType( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initType(unsigned int size);
  inline void adoptType(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownType();

  inline bool hasMessage();
  inline  ::capnp::Text::Builder getMessage();
  inline void setMessage( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initMessage(unsigned int size);
  inline void adoptMessage(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownMessage();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ErrorVal::Pipeline {
public:
  typedef ErrorVal Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Message::Reader {
public:
  typedef Message Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isPush() const;
  inline bool hasPush() const;
  inline  ::Expression::Reader getPush() const;

  inline bool isPull() const;
  inline  ::int64_t getPull() const;

  inline bool isResolve() const;
  inline bool hasResolve() const;
  inline  ::ResolveReject::Reader getResolve() const;

  inline bool isReject() const;
  inline bool hasReject() const;
  inline  ::ResolveReject::Reader getReject() const;

  inline bool isRelease() const;
  inline bool hasRelease() const;
  inline  ::Release::Reader getRelease() const;

  inline bool isStream() const;
  inline bool hasStream() const;
  inline  ::Expression::Reader getStream() const;

  inline bool isAbort() const;
  inline bool hasAbort() const;
  inline  ::Expression::Reader getAbort() const;

  inline bool isPipe() const;
  inline  ::capnp::Void getPipe() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Message::Builder {
public:
  typedef Message Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isPush();
  inline bool hasPush();
  inline  ::Expression::Builder getPush();
  inline void setPush( ::Expression::Reader value);
  inline  ::Expression::Builder initPush();
  inline void adoptPush(::capnp::Orphan< ::Expression>&& value);
  inline ::capnp::Orphan< ::Expression> disownPush();

  inline bool isPull();
  inline  ::int64_t getPull();
  inline void setPull( ::int64_t value);

  inline bool isResolve();
  inline bool hasResolve();
  inline  ::ResolveReject::Builder getResolve();
  inline void setResolve( ::ResolveReject::Reader value);
  inline  ::ResolveReject::Builder initResolve();
  inline void adoptResolve(::capnp::Orphan< ::ResolveReject>&& value);
  inline ::capnp::Orphan< ::ResolveReject> disownResolve();

  inline bool isReject();
  inline bool hasReject();
  inline  ::ResolveReject::Builder getReject();
  inline void setReject( ::ResolveReject::Reader value);
  inline  ::ResolveReject::Builder initReject();
  inline void adoptReject(::capnp::Orphan< ::ResolveReject>&& value);
  inline ::capnp::Orphan< ::ResolveReject> disownReject();

  inline bool isRelease();
  inline bool hasRelease();
  inline  ::Release::Builder getRelease();
  inline void setRelease( ::Release::Reader value);
  inline  ::Release::Builder initRelease();
  inline void adoptRelease(::capnp::Orphan< ::Release>&& value);
  inline ::capnp::Orphan< ::Release> disownRelease();

  inline bool isStream();
  inline bool hasStream();
  inline  ::Expression::Builder getStream();
  inline void setStream( ::Expression::Reader value);
  inline  ::Expression::Builder initStream();
  inline void adoptStream(::capnp::Orphan< ::Expression>&& value);
  inline ::capnp::Orphan< ::Expression> disownStream();

  inline bool isAbort();
  inline bool hasAbort();
  inline  ::Expression::Builder getAbort();
  inline void setAbort( ::Expression::Reader value);
  inline  ::Expression::Builder initAbort();
  inline void adoptAbort(::capnp::Orphan< ::Expression>&& value);
  inline ::capnp::Orphan< ::Expression> disownAbort();

  inline bool isPipe();
  inline  ::capnp::Void getPipe();
  inline void setPipe( ::capnp::Void value = ::capnp::VOID);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Message::Pipeline {
public:
  typedef Message Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class ResolveReject::Reader {
public:
  typedef ResolveReject Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::int64_t getId() const;

  inline bool hasExpr() const;
  inline  ::Expression::Reader getExpr() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ResolveReject::Builder {
public:
  typedef ResolveReject Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::int64_t getId();
  inline void setId( ::int64_t value);

  inline bool hasExpr();
  inline  ::Expression::Builder getExpr();
  inline void setExpr( ::Expression::Reader value);
  inline  ::Expression::Builder initExpr();
  inline void adoptExpr(::capnp::Orphan< ::Expression>&& value);
  inline ::capnp::Orphan< ::Expression> disownExpr();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ResolveReject::Pipeline {
public:
  typedef ResolveReject Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::Expression::Pipeline getExpr();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Release::Reader {
public:
  typedef Release Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::int64_t getId() const;

  inline  ::uint32_t getRefcount() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Release::Builder {
public:
  typedef Release Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::int64_t getId();
  inline void setId( ::int64_t value);

  inline  ::uint32_t getRefcount();
  inline void setRefcount( ::uint32_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Release::Pipeline {
public:
  typedef Release Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::Expression::Which Expression::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline  ::Expression::Which Expression::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool Expression::Reader::isNullVal() const {
  return which() == Expression::NULL_VAL;
}
inline bool Expression::Builder::isNullVal() {
  return which() == Expression::NULL_VAL;
}
inline  ::capnp::Void Expression::Reader::getNullVal() const {
  KJ_IREQUIRE((which() == Expression::NULL_VAL),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Expression::Builder::getNullVal() {
  KJ_IREQUIRE((which() == Expression::NULL_VAL),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Expression::Builder::setNullVal( ::capnp::Void value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::NULL_VAL);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Expression::Reader::isBoolFalse() const {
  return which() == Expression::BOOL_FALSE;
}
inline bool Expression::Builder::isBoolFalse() {
  return which() == Expression::BOOL_FALSE;
}
inline  ::capnp::Void Expression::Reader::getBoolFalse() const {
  KJ_IREQUIRE((which() == Expression::BOOL_FALSE),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Expression::Builder::getBoolFalse() {
  KJ_IREQUIRE((which() == Expression::BOOL_FALSE),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Expression::Builder::setBoolFalse( ::capnp::Void value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::BOOL_FALSE);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Expression::Reader::isBoolTrue() const {
  return which() == Expression::BOOL_TRUE;
}
inline bool Expression::Builder::isBoolTrue() {
  return which() == Expression::BOOL_TRUE;
}
inline  ::capnp::Void Expression::Reader::getBoolTrue() const {
  KJ_IREQUIRE((which() == Expression::BOOL_TRUE),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Expression::Builder::getBoolTrue() {
  KJ_IREQUIRE((which() == Expression::BOOL_TRUE),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Expression::Builder::setBoolTrue( ::capnp::Void value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::BOOL_TRUE);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Expression::Reader::isIntVal() const {
  return which() == Expression::INT_VAL;
}
inline bool Expression::Builder::isIntVal() {
  return which() == Expression::INT_VAL;
}
inline  ::int64_t Expression::Reader::getIntVal() const {
  KJ_IREQUIRE((which() == Expression::INT_VAL),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::int64_t Expression::Builder::getIntVal() {
  KJ_IREQUIRE((which() == Expression::INT_VAL),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void Expression::Builder::setIntVal( ::int64_t value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::INT_VAL);
  _builder.setDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline bool Expression::Reader::isFloatVal() const {
  return which() == Expression::FLOAT_VAL;
}
inline bool Expression::Builder::isFloatVal() {
  return which() == Expression::FLOAT_VAL;
}
inline double Expression::Reader::getFloatVal() const {
  KJ_IREQUIRE((which() == Expression::FLOAT_VAL),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField<double>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline double Expression::Builder::getFloatVal() {
  KJ_IREQUIRE((which() == Expression::FLOAT_VAL),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField<double>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void Expression::Builder::setFloatVal(double value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::FLOAT_VAL);
  _builder.setDataField<double>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline bool Expression::Reader::isText() const {
  return which() == Expression::TEXT;
}
inline bool Expression::Builder::isText() {
  return which() == Expression::TEXT;
}
inline bool Expression::Reader::hasText() const {
  if (which() != Expression::TEXT) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Expression::Builder::hasText() {
  if (which() != Expression::TEXT) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader Expression::Reader::getText() const {
  KJ_IREQUIRE((which() == Expression::TEXT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder Expression::Builder::getText() {
  KJ_IREQUIRE((which() == Expression::TEXT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Expression::Builder::setText( ::capnp::Text::Reader value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::TEXT);
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder Expression::Builder::initText(unsigned int size) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::TEXT);
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Expression::Builder::adoptText(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::TEXT);
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> Expression::Builder::disownText() {
  KJ_IREQUIRE((which() == Expression::TEXT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Expression::Reader::isData() const {
  return which() == Expression::DATA;
}
inline bool Expression::Builder::isData() {
  return which() == Expression::DATA;
}
inline bool Expression::Reader::hasData() const {
  if (which() != Expression::DATA) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Expression::Builder::hasData() {
  if (which() != Expression::DATA) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Data::Reader Expression::Reader::getData() const {
  KJ_IREQUIRE((which() == Expression::DATA),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Data::Builder Expression::Builder::getData() {
  KJ_IREQUIRE((which() == Expression::DATA),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Expression::Builder::setData( ::capnp::Data::Reader value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::DATA);
  ::capnp::_::PointerHelpers< ::capnp::Data>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Data::Builder Expression::Builder::initData(unsigned int size) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::DATA);
  return ::capnp::_::PointerHelpers< ::capnp::Data>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Expression::Builder::adoptData(
    ::capnp::Orphan< ::capnp::Data>&& value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::DATA);
  ::capnp::_::PointerHelpers< ::capnp::Data>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Data> Expression::Builder::disownData() {
  KJ_IREQUIRE((which() == Expression::DATA),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Data>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Expression::Reader::isArray() const {
  return which() == Expression::ARRAY;
}
inline bool Expression::Builder::isArray() {
  return which() == Expression::ARRAY;
}
inline bool Expression::Reader::hasArray() const {
  if (which() != Expression::ARRAY) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Expression::Builder::hasArray() {
  if (which() != Expression::ARRAY) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>::Reader Expression::Reader::getArray() const {
  KJ_IREQUIRE((which() == Expression::ARRAY),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>::Builder Expression::Builder::getArray() {
  KJ_IREQUIRE((which() == Expression::ARRAY),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Expression::Builder::setArray( ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>::Reader value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::ARRAY);
  ::capnp::_::PointerHelpers< ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>::Builder Expression::Builder::initArray(unsigned int size) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::ARRAY);
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Expression::Builder::adoptArray(
    ::capnp::Orphan< ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>>&& value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::ARRAY);
  ::capnp::_::PointerHelpers< ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>> Expression::Builder::disownArray() {
  KJ_IREQUIRE((which() == Expression::ARRAY),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Expression,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Expression::Reader::isObject() const {
  return which() == Expression::OBJECT;
}
inline bool Expression::Builder::isObject() {
  return which() == Expression::OBJECT;
}
inline bool Expression::Reader::hasObject() const {
  if (which() != Expression::OBJECT) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Expression::Builder::hasObject() {
  if (which() != Expression::OBJECT) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>::Reader Expression::Reader::getObject() const {
  KJ_IREQUIRE((which() == Expression::OBJECT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>::Builder Expression::Builder::getObject() {
  KJ_IREQUIRE((which() == Expression::OBJECT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Expression::Builder::setObject( ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>::Reader value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::OBJECT);
  ::capnp::_::PointerHelpers< ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>::Builder Expression::Builder::initObject(unsigned int size) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::OBJECT);
  return ::capnp::_::PointerHelpers< ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Expression::Builder::adoptObject(
    ::capnp::Orphan< ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>>&& value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::OBJECT);
  ::capnp::_::PointerHelpers< ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>> Expression::Builder::disownObject() {
  KJ_IREQUIRE((which() == Expression::OBJECT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List< ::KeyValue,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Expression::Reader::isImportRef() const {
  return which() == Expression::IMPORT_REF;
}
inline bool Expression::Builder::isImportRef() {
  return which() == Expression::IMPORT_REF;
}
inline  ::int64_t Expression::Reader::getImportRef() const {
  KJ_IREQUIRE((which() == Expression::IMPORT_REF),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::int64_t Expression::Builder::getImportRef() {
  KJ_IREQUIRE((which() == Expression::IMPORT_REF),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void Expression::Builder::setImportRef( ::int64_t value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::IMPORT_REF);
  _builder.setDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline bool Expression::Reader::isExportRef() const {
  return which() == Expression::EXPORT_REF;
}
inline bool Expression::Builder::isExportRef() {
  return which() == Expression::EXPORT_REF;
}
inline  ::int64_t Expression::Reader::getExportRef() const {
  KJ_IREQUIRE((which() == Expression::EXPORT_REF),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::int64_t Expression::Builder::getExportRef() {
  KJ_IREQUIRE((which() == Expression::EXPORT_REF),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void Expression::Builder::setExportRef( ::int64_t value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::EXPORT_REF);
  _builder.setDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline bool Expression::Reader::isPipeline() const {
  return which() == Expression::PIPELINE;
}
inline bool Expression::Builder::isPipeline() {
  return which() == Expression::PIPELINE;
}
inline bool Expression::Reader::hasPipeline() const {
  if (which() != Expression::PIPELINE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Expression::Builder::hasPipeline() {
  if (which() != Expression::PIPELINE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::PipelineExpr::Reader Expression::Reader::getPipeline() const {
  KJ_IREQUIRE((which() == Expression::PIPELINE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::PipelineExpr>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::PipelineExpr::Builder Expression::Builder::getPipeline() {
  KJ_IREQUIRE((which() == Expression::PIPELINE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::PipelineExpr>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Expression::Builder::setPipeline( ::PipelineExpr::Reader value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::PIPELINE);
  ::capnp::_::PointerHelpers< ::PipelineExpr>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::PipelineExpr::Builder Expression::Builder::initPipeline() {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::PIPELINE);
  return ::capnp::_::PointerHelpers< ::PipelineExpr>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Expression::Builder::adoptPipeline(
    ::capnp::Orphan< ::PipelineExpr>&& value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::PIPELINE);
  ::capnp::_::PointerHelpers< ::PipelineExpr>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::PipelineExpr> Expression::Builder::disownPipeline() {
  KJ_IREQUIRE((which() == Expression::PIPELINE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::PipelineExpr>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Expression::Reader::isErrorVal() const {
  return which() == Expression::ERROR_VAL;
}
inline bool Expression::Builder::isErrorVal() {
  return which() == Expression::ERROR_VAL;
}
inline bool Expression::Reader::hasErrorVal() const {
  if (which() != Expression::ERROR_VAL) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Expression::Builder::hasErrorVal() {
  if (which() != Expression::ERROR_VAL) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::ErrorVal::Reader Expression::Reader::getErrorVal() const {
  KJ_IREQUIRE((which() == Expression::ERROR_VAL),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ErrorVal>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::ErrorVal::Builder Expression::Builder::getErrorVal() {
  KJ_IREQUIRE((which() == Expression::ERROR_VAL),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ErrorVal>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Expression::Builder::setErrorVal( ::ErrorVal::Reader value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::ERROR_VAL);
  ::capnp::_::PointerHelpers< ::ErrorVal>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::ErrorVal::Builder Expression::Builder::initErrorVal() {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::ERROR_VAL);
  return ::capnp::_::PointerHelpers< ::ErrorVal>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Expression::Builder::adoptErrorVal(
    ::capnp::Orphan< ::ErrorVal>&& value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::ERROR_VAL);
  ::capnp::_::PointerHelpers< ::ErrorVal>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::ErrorVal> Expression::Builder::disownErrorVal() {
  KJ_IREQUIRE((which() == Expression::ERROR_VAL),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ErrorVal>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Expression::Reader::isDate() const {
  return which() == Expression::DATE;
}
inline bool Expression::Builder::isDate() {
  return which() == Expression::DATE;
}
inline double Expression::Reader::getDate() const {
  KJ_IREQUIRE((which() == Expression::DATE),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField<double>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline double Expression::Builder::getDate() {
  KJ_IREQUIRE((which() == Expression::DATE),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField<double>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void Expression::Builder::setDate(double value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::DATE);
  _builder.setDataField<double>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline bool Expression::Reader::isBigint() const {
  return which() == Expression::BIGINT;
}
inline bool Expression::Builder::isBigint() {
  return which() == Expression::BIGINT;
}
inline bool Expression::Reader::hasBigint() const {
  if (which() != Expression::BIGINT) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Expression::Builder::hasBigint() {
  if (which() != Expression::BIGINT) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader Expression::Reader::getBigint() const {
  KJ_IREQUIRE((which() == Expression::BIGINT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder Expression::Builder::getBigint() {
  KJ_IREQUIRE((which() == Expression::BIGINT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Expression::Builder::setBigint( ::capnp::Text::Reader value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::BIGINT);
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder Expression::Builder::initBigint(unsigned int size) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::BIGINT);
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Expression::Builder::adoptBigint(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::BIGINT);
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> Expression::Builder::disownBigint() {
  KJ_IREQUIRE((which() == Expression::BIGINT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Expression::Reader::isUndefinedVal() const {
  return which() == Expression::UNDEFINED_VAL;
}
inline bool Expression::Builder::isUndefinedVal() {
  return which() == Expression::UNDEFINED_VAL;
}
inline  ::capnp::Void Expression::Reader::getUndefinedVal() const {
  KJ_IREQUIRE((which() == Expression::UNDEFINED_VAL),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Expression::Builder::getUndefinedVal() {
  KJ_IREQUIRE((which() == Expression::UNDEFINED_VAL),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Expression::Builder::setUndefinedVal( ::capnp::Void value) {
  _builder.setDataField<Expression::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Expression::UNDEFINED_VAL);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool KeyValue::Reader::hasKey() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool KeyValue::Builder::hasKey() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader KeyValue::Reader::getKey() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder KeyValue::Builder::getKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void KeyValue::Builder::setKey( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder KeyValue::Builder::initKey(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void KeyValue::Builder::adoptKey(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> KeyValue::Builder::disownKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool KeyValue::Reader::hasValue() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool KeyValue::Builder::hasValue() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::Expression::Reader KeyValue::Reader::getValue() const {
  return ::capnp::_::PointerHelpers< ::Expression>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::Expression::Builder KeyValue::Builder::getValue() {
  return ::capnp::_::PointerHelpers< ::Expression>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::Expression::Pipeline KeyValue::Pipeline::getValue() {
  return  ::Expression::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void KeyValue::Builder::setValue( ::Expression::Reader value) {
  ::capnp::_::PointerHelpers< ::Expression>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::Expression::Builder KeyValue::Builder::initValue() {
  return ::capnp::_::PointerHelpers< ::Expression>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void KeyValue::Builder::adoptValue(
    ::capnp::Orphan< ::Expression>&& value) {
  ::capnp::_::PointerHelpers< ::Expression>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Expression> KeyValue::Builder::disownValue() {
  return ::capnp::_::PointerHelpers< ::Expression>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool PipelineExpr::Reader::hasSource() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool PipelineExpr::Builder::hasSource() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Expression::Reader PipelineExpr::Reader::getSource() const {
  return ::capnp::_::PointerHelpers< ::Expression>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Expression::Builder PipelineExpr::Builder::getSource() {
  return ::capnp::_::PointerHelpers< ::Expression>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::Expression::Pipeline PipelineExpr::Pipeline::getSource() {
  return  ::Expression::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void PipelineExpr::Builder::setSource( ::Expression::Reader value) {
  ::capnp::_::PointerHelpers< ::Expression>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Expression::Builder PipelineExpr::Builder::initSource() {
  return ::capnp::_::PointerHelpers< ::Expression>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void PipelineExpr::Builder::adoptSource(
    ::capnp::Orphan< ::Expression>&& value) {
  ::capnp::_::PointerHelpers< ::Expression>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Expression> PipelineExpr::Builder::disownSource() {
  return ::capnp::_::PointerHelpers< ::Expression>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool PipelineExpr::Reader::hasPath() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool PipelineExpr::Builder::hasPath() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>::Reader PipelineExpr::Reader::getPath() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>::Builder PipelineExpr::Builder::getPath() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void PipelineExpr::Builder::setPath( ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline void PipelineExpr::Builder::setPath(::kj::ArrayPtr<const  ::capnp::Text::Reader> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>::Builder PipelineExpr::Builder::initPath(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void PipelineExpr::Builder::adoptPath(
    ::capnp::Orphan< ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>> PipelineExpr::Builder::disownPath() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnp::Text,  ::capnp::Kind::BLOB>>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool PipelineExpr::Reader::hasArgs() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool PipelineExpr::Builder::hasArgs() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::Expression::Reader PipelineExpr::Reader::getArgs() const {
  return ::capnp::_::PointerHelpers< ::Expression>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::Expression::Builder PipelineExpr::Builder::getArgs() {
  return ::capnp::_::PointerHelpers< ::Expression>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::Expression::Pipeline PipelineExpr::Pipeline::getArgs() {
  return  ::Expression::Pipeline(_typeless.getPointerField(2));
}
#endif  // !CAPNP_LITE
inline void PipelineExpr::Builder::setArgs( ::Expression::Reader value) {
  ::capnp::_::PointerHelpers< ::Expression>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::Expression::Builder PipelineExpr::Builder::initArgs() {
  return ::capnp::_::PointerHelpers< ::Expression>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void PipelineExpr::Builder::adoptArgs(
    ::capnp::Orphan< ::Expression>&& value) {
  ::capnp::_::PointerHelpers< ::Expression>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Expression> PipelineExpr::Builder::disownArgs() {
  return ::capnp::_::PointerHelpers< ::Expression>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline bool ErrorVal::Reader::hasType() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool ErrorVal::Builder::hasType() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader ErrorVal::Reader::getType() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder ErrorVal::Builder::getType() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ErrorVal::Builder::setType( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder ErrorVal::Builder::initType(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void ErrorVal::Builder::adoptType(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> ErrorVal::Builder::disownType() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool ErrorVal::Reader::hasMessage() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool ErrorVal::Builder::hasMessage() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader ErrorVal::Reader::getMessage() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder ErrorVal::Builder::getMessage() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void ErrorVal::Builder::setMessage( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder ErrorVal::Builder::initMessage(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void ErrorVal::Builder::adoptMessage(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> ErrorVal::Builder::disownMessage() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline  ::Message::Which Message::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline  ::Message::Which Message::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool Message::Reader::isPush() const {
  return which() == Message::PUSH;
}
inline bool Message::Builder::isPush() {
  return which() == Message::PUSH;
}
inline bool Message::Reader::hasPush() const {
  if (which() != Message::PUSH) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Message::Builder::hasPush() {
  if (which() != Message::PUSH) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Expression::Reader Message::Reader::getPush() const {
  KJ_IREQUIRE((which() == Message::PUSH),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Expression>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Expression::Builder Message::Builder::getPush() {
  KJ_IREQUIRE((which() == Message::PUSH),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Expression>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::setPush( ::Expression::Reader value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::PUSH);
  ::capnp::_::PointerHelpers< ::Expression>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Expression::Builder Message::Builder::initPush() {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::PUSH);
  return ::capnp::_::PointerHelpers< ::Expression>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::adoptPush(
    ::capnp::Orphan< ::Expression>&& value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::PUSH);
  ::capnp::_::PointerHelpers< ::Expression>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Expression> Message::Builder::disownPush() {
  KJ_IREQUIRE((which() == Message::PUSH),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Expression>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Message::Reader::isPull() const {
  return which() == Message::PULL;
}
inline bool Message::Builder::isPull() {
  return which() == Message::PULL;
}
inline  ::int64_t Message::Reader::getPull() const {
  KJ_IREQUIRE((which() == Message::PULL),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::int64_t Message::Builder::getPull() {
  KJ_IREQUIRE((which() == Message::PULL),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void Message::Builder::setPull( ::int64_t value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::PULL);
  _builder.setDataField< ::int64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline bool Message::Reader::isResolve() const {
  return which() == Message::RESOLVE;
}
inline bool Message::Builder::isResolve() {
  return which() == Message::RESOLVE;
}
inline bool Message::Reader::hasResolve() const {
  if (which() != Message::RESOLVE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Message::Builder::hasResolve() {
  if (which() != Message::RESOLVE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::ResolveReject::Reader Message::Reader::getResolve() const {
  KJ_IREQUIRE((which() == Message::RESOLVE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ResolveReject>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::ResolveReject::Builder Message::Builder::getResolve() {
  KJ_IREQUIRE((which() == Message::RESOLVE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ResolveReject>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::setResolve( ::ResolveReject::Reader value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::RESOLVE);
  ::capnp::_::PointerHelpers< ::ResolveReject>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::ResolveReject::Builder Message::Builder::initResolve() {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::RESOLVE);
  return ::capnp::_::PointerHelpers< ::ResolveReject>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::adoptResolve(
    ::capnp::Orphan< ::ResolveReject>&& value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::RESOLVE);
  ::capnp::_::PointerHelpers< ::ResolveReject>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::ResolveReject> Message::Builder::disownResolve() {
  KJ_IREQUIRE((which() == Message::RESOLVE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ResolveReject>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Message::Reader::isReject() const {
  return which() == Message::REJECT;
}
inline bool Message::Builder::isReject() {
  return which() == Message::REJECT;
}
inline bool Message::Reader::hasReject() const {
  if (which() != Message::REJECT) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Message::Builder::hasReject() {
  if (which() != Message::REJECT) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::ResolveReject::Reader Message::Reader::getReject() const {
  KJ_IREQUIRE((which() == Message::REJECT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ResolveReject>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::ResolveReject::Builder Message::Builder::getReject() {
  KJ_IREQUIRE((which() == Message::REJECT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ResolveReject>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::setReject( ::ResolveReject::Reader value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::REJECT);
  ::capnp::_::PointerHelpers< ::ResolveReject>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::ResolveReject::Builder Message::Builder::initReject() {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::REJECT);
  return ::capnp::_::PointerHelpers< ::ResolveReject>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::adoptReject(
    ::capnp::Orphan< ::ResolveReject>&& value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::REJECT);
  ::capnp::_::PointerHelpers< ::ResolveReject>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::ResolveReject> Message::Builder::disownReject() {
  KJ_IREQUIRE((which() == Message::REJECT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ResolveReject>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Message::Reader::isRelease() const {
  return which() == Message::RELEASE;
}
inline bool Message::Builder::isRelease() {
  return which() == Message::RELEASE;
}
inline bool Message::Reader::hasRelease() const {
  if (which() != Message::RELEASE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Message::Builder::hasRelease() {
  if (which() != Message::RELEASE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Release::Reader Message::Reader::getRelease() const {
  KJ_IREQUIRE((which() == Message::RELEASE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Release>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Release::Builder Message::Builder::getRelease() {
  KJ_IREQUIRE((which() == Message::RELEASE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Release>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::setRelease( ::Release::Reader value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::RELEASE);
  ::capnp::_::PointerHelpers< ::Release>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Release::Builder Message::Builder::initRelease() {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::RELEASE);
  return ::capnp::_::PointerHelpers< ::Release>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::adoptRelease(
    ::capnp::Orphan< ::Release>&& value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::RELEASE);
  ::capnp::_::PointerHelpers< ::Release>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Release> Message::Builder::disownRelease() {
  KJ_IREQUIRE((which() == Message::RELEASE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Release>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Message::Reader::isStream() const {
  return which() == Message::STREAM;
}
inline bool Message::Builder::isStream() {
  return which() == Message::STREAM;
}
inline bool Message::Reader::hasStream() const {
  if (which() != Message::STREAM) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Message::Builder::hasStream() {
  if (which() != Message::STREAM) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Expression::Reader Message::Reader::getStream() const {
  KJ_IREQUIRE((which() == Message::STREAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Expression>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Expression::Builder Message::Builder::getStream() {
  KJ_IREQUIRE((which() == Message::STREAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Expression>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::setStream( ::Expression::Reader value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::STREAM);
  ::capnp::_::PointerHelpers< ::Expression>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Expression::Builder Message::Builder::initStream() {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::STREAM);
  return ::capnp::_::PointerHelpers< ::Expression>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::adoptStream(
    ::capnp::Orphan< ::Expression>&& value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::STREAM);
  ::capnp::_::PointerHelpers< ::Expression>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Expression> Message::Builder::disownStream() {
  KJ_IREQUIRE((which() == Message::STREAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Expression>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Message::Reader::isAbort() const {
  return which() == Message::ABORT;
}
inline bool Message::Builder::isAbort() {
  return which() == Message::ABORT;
}
inline bool Message::Reader::hasAbort() const {
  if (which() != Message::ABORT) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Message::Builder::hasAbort() {
  if (which() != Message::ABORT) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Expression::Reader Message::Reader::getAbort() const {
  KJ_IREQUIRE((which() == Message::ABORT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Expression>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Expression::Builder Message::Builder::getAbort() {
  KJ_IREQUIRE((which() == Message::ABORT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Expression>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::setAbort( ::Expression::Reader value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::ABORT);
  ::capnp::_::PointerHelpers< ::Expression>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Expression::Builder Message::Builder::initAbort() {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::ABORT);
  return ::capnp::_::PointerHelpers< ::Expression>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Builder::adoptAbort(
    ::capnp::Orphan< ::Expression>&& value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::ABORT);
  ::capnp::_::PointerHelpers< ::Expression>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Expression> Message::Builder::disownAbort() {
  KJ_IREQUIRE((which() == Message::ABORT),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Expression>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Message::Reader::isPipe() const {
  return which() == Message::PIPE;
}
inline bool Message::Builder::isPipe() {
  return which() == Message::PIPE;
}
inline  ::capnp::Void Message::Reader::getPipe() const {
  KJ_IREQUIRE((which() == Message::PIPE),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Message::Builder::getPipe() {
  KJ_IREQUIRE((which() == Message::PIPE),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Message::Builder::setPipe( ::capnp::Void value) {
  _builder.setDataField<Message::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::PIPE);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::int64_t ResolveReject::Reader::getId() const {
  return _reader.getDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::int64_t ResolveReject::Builder::getId() {
  return _builder.getDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void ResolveReject::Builder::setId( ::int64_t value) {
  _builder.setDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool ResolveReject::Reader::hasExpr() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool ResolveReject::Builder::hasExpr() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Expression::Reader ResolveReject::Reader::getExpr() const {
  return ::capnp::_::PointerHelpers< ::Expression>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Expression::Builder ResolveReject::Builder::getExpr() {
  return ::capnp::_::PointerHelpers< ::Expression>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::Expression::Pipeline ResolveReject::Pipeline::getExpr() {
  return  ::Expression::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void ResolveReject::Builder::setExpr( ::Expression::Reader value) {
  ::capnp::_::PointerHelpers< ::Expression>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Expression::Builder ResolveReject::Builder::initExpr() {
  return ::capnp::_::PointerHelpers< ::Expression>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ResolveReject::Builder::adoptExpr(
    ::capnp::Orphan< ::Expression>&& value) {
  ::capnp::_::PointerHelpers< ::Expression>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Expression> ResolveReject::Builder::disownExpr() {
  return ::capnp::_::PointerHelpers< ::Expression>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::int64_t Release::Reader::getId() const {
  return _reader.getDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::int64_t Release::Builder::getId() {
  return _builder.getDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Release::Builder::setId( ::int64_t value) {
  _builder.setDataField< ::int64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint32_t Release::Reader::getRefcount() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Release::Builder::getRefcount() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Release::Builder::setRefcount( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}


CAPNP_END_HEADER

