// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: typed_schema.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 2000000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(b22c52010f53b172);

}  // namespace schemas
}  // namespace capnp


struct WideUserData {
  WideUserData() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(b22c52010f53b172, 0, 32)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class WideUserData::Reader {
public:
  typedef WideUserData Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasField0() const;
  inline  ::capnp::Text::Reader getField0() const;

  inline bool hasField1() const;
  inline  ::capnp::Text::Reader getField1() const;

  inline bool hasField2() const;
  inline  ::capnp::Text::Reader getField2() const;

  inline bool hasField3() const;
  inline  ::capnp::Text::Reader getField3() const;

  inline bool hasField4() const;
  inline  ::capnp::Text::Reader getField4() const;

  inline bool hasField5() const;
  inline  ::capnp::Text::Reader getField5() const;

  inline bool hasField6() const;
  inline  ::capnp::Text::Reader getField6() const;

  inline bool hasField7() const;
  inline  ::capnp::Text::Reader getField7() const;

  inline bool hasField8() const;
  inline  ::capnp::Text::Reader getField8() const;

  inline bool hasField9() const;
  inline  ::capnp::Text::Reader getField9() const;

  inline bool hasField10() const;
  inline  ::capnp::Text::Reader getField10() const;

  inline bool hasField11() const;
  inline  ::capnp::Text::Reader getField11() const;

  inline bool hasField12() const;
  inline  ::capnp::Text::Reader getField12() const;

  inline bool hasField13() const;
  inline  ::capnp::Text::Reader getField13() const;

  inline bool hasField14() const;
  inline  ::capnp::Text::Reader getField14() const;

  inline bool hasField15() const;
  inline  ::capnp::Text::Reader getField15() const;

  inline bool hasField16() const;
  inline  ::capnp::Text::Reader getField16() const;

  inline bool hasField17() const;
  inline  ::capnp::Text::Reader getField17() const;

  inline bool hasField18() const;
  inline  ::capnp::Text::Reader getField18() const;

  inline bool hasField19() const;
  inline  ::capnp::Text::Reader getField19() const;

  inline bool hasField20() const;
  inline  ::capnp::Text::Reader getField20() const;

  inline bool hasField21() const;
  inline  ::capnp::Text::Reader getField21() const;

  inline bool hasField22() const;
  inline  ::capnp::Text::Reader getField22() const;

  inline bool hasField23() const;
  inline  ::capnp::Text::Reader getField23() const;

  inline bool hasField24() const;
  inline  ::capnp::Text::Reader getField24() const;

  inline bool hasField25() const;
  inline  ::capnp::Text::Reader getField25() const;

  inline bool hasField26() const;
  inline  ::capnp::Text::Reader getField26() const;

  inline bool hasField27() const;
  inline  ::capnp::Text::Reader getField27() const;

  inline bool hasField28() const;
  inline  ::capnp::Text::Reader getField28() const;

  inline bool hasField29() const;
  inline  ::capnp::Text::Reader getField29() const;

  inline bool hasField30() const;
  inline  ::capnp::Text::Reader getField30() const;

  inline bool hasField31() const;
  inline  ::capnp::Text::Reader getField31() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class WideUserData::Builder {
public:
  typedef WideUserData Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasField0();
  inline  ::capnp::Text::Builder getField0();
  inline void setField0( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField0(unsigned int size);
  inline void adoptField0(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField0();

  inline bool hasField1();
  inline  ::capnp::Text::Builder getField1();
  inline void setField1( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField1(unsigned int size);
  inline void adoptField1(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField1();

  inline bool hasField2();
  inline  ::capnp::Text::Builder getField2();
  inline void setField2( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField2(unsigned int size);
  inline void adoptField2(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField2();

  inline bool hasField3();
  inline  ::capnp::Text::Builder getField3();
  inline void setField3( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField3(unsigned int size);
  inline void adoptField3(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField3();

  inline bool hasField4();
  inline  ::capnp::Text::Builder getField4();
  inline void setField4( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField4(unsigned int size);
  inline void adoptField4(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField4();

  inline bool hasField5();
  inline  ::capnp::Text::Builder getField5();
  inline void setField5( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField5(unsigned int size);
  inline void adoptField5(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField5();

  inline bool hasField6();
  inline  ::capnp::Text::Builder getField6();
  inline void setField6( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField6(unsigned int size);
  inline void adoptField6(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField6();

  inline bool hasField7();
  inline  ::capnp::Text::Builder getField7();
  inline void setField7( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField7(unsigned int size);
  inline void adoptField7(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField7();

  inline bool hasField8();
  inline  ::capnp::Text::Builder getField8();
  inline void setField8( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField8(unsigned int size);
  inline void adoptField8(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField8();

  inline bool hasField9();
  inline  ::capnp::Text::Builder getField9();
  inline void setField9( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField9(unsigned int size);
  inline void adoptField9(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField9();

  inline bool hasField10();
  inline  ::capnp::Text::Builder getField10();
  inline void setField10( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField10(unsigned int size);
  inline void adoptField10(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField10();

  inline bool hasField11();
  inline  ::capnp::Text::Builder getField11();
  inline void setField11( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField11(unsigned int size);
  inline void adoptField11(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField11();

  inline bool hasField12();
  inline  ::capnp::Text::Builder getField12();
  inline void setField12( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField12(unsigned int size);
  inline void adoptField12(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField12();

  inline bool hasField13();
  inline  ::capnp::Text::Builder getField13();
  inline void setField13( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField13(unsigned int size);
  inline void adoptField13(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField13();

  inline bool hasField14();
  inline  ::capnp::Text::Builder getField14();
  inline void setField14( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField14(unsigned int size);
  inline void adoptField14(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField14();

  inline bool hasField15();
  inline  ::capnp::Text::Builder getField15();
  inline void setField15( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField15(unsigned int size);
  inline void adoptField15(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField15();

  inline bool hasField16();
  inline  ::capnp::Text::Builder getField16();
  inline void setField16( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField16(unsigned int size);
  inline void adoptField16(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField16();

  inline bool hasField17();
  inline  ::capnp::Text::Builder getField17();
  inline void setField17( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField17(unsigned int size);
  inline void adoptField17(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField17();

  inline bool hasField18();
  inline  ::capnp::Text::Builder getField18();
  inline void setField18( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField18(unsigned int size);
  inline void adoptField18(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField18();

  inline bool hasField19();
  inline  ::capnp::Text::Builder getField19();
  inline void setField19( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField19(unsigned int size);
  inline void adoptField19(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField19();

  inline bool hasField20();
  inline  ::capnp::Text::Builder getField20();
  inline void setField20( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField20(unsigned int size);
  inline void adoptField20(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField20();

  inline bool hasField21();
  inline  ::capnp::Text::Builder getField21();
  inline void setField21( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField21(unsigned int size);
  inline void adoptField21(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField21();

  inline bool hasField22();
  inline  ::capnp::Text::Builder getField22();
  inline void setField22( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField22(unsigned int size);
  inline void adoptField22(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField22();

  inline bool hasField23();
  inline  ::capnp::Text::Builder getField23();
  inline void setField23( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField23(unsigned int size);
  inline void adoptField23(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField23();

  inline bool hasField24();
  inline  ::capnp::Text::Builder getField24();
  inline void setField24( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField24(unsigned int size);
  inline void adoptField24(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField24();

  inline bool hasField25();
  inline  ::capnp::Text::Builder getField25();
  inline void setField25( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField25(unsigned int size);
  inline void adoptField25(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField25();

  inline bool hasField26();
  inline  ::capnp::Text::Builder getField26();
  inline void setField26( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField26(unsigned int size);
  inline void adoptField26(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField26();

  inline bool hasField27();
  inline  ::capnp::Text::Builder getField27();
  inline void setField27( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField27(unsigned int size);
  inline void adoptField27(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField27();

  inline bool hasField28();
  inline  ::capnp::Text::Builder getField28();
  inline void setField28( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField28(unsigned int size);
  inline void adoptField28(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField28();

  inline bool hasField29();
  inline  ::capnp::Text::Builder getField29();
  inline void setField29( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField29(unsigned int size);
  inline void adoptField29(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField29();

  inline bool hasField30();
  inline  ::capnp::Text::Builder getField30();
  inline void setField30( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField30(unsigned int size);
  inline void adoptField30(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField30();

  inline bool hasField31();
  inline  ::capnp::Text::Builder getField31();
  inline void setField31( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initField31(unsigned int size);
  inline void adoptField31(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownField31();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class WideUserData::Pipeline {
public:
  typedef WideUserData Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool WideUserData::Reader::hasField0() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField0() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField0() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField0() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField0( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField0(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField0(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField0() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField1() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField1() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField1() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField1() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField1( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField1(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField1(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField1() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField2() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField2() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField2() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField2() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField2( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField2(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField2(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField2() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField3() const {
  return !_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField3() {
  return !_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField3() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField3() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField3( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField3(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField3(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField3() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField4() const {
  return !_reader.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField4() {
  return !_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField4() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField4() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField4( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField4(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField4(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField4() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField5() const {
  return !_reader.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField5() {
  return !_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField5() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField5() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField5( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField5(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField5(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField5() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField6() const {
  return !_reader.getPointerField(
      ::capnp::bounded<6>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField6() {
  return !_builder.getPointerField(
      ::capnp::bounded<6>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField6() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<6>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField6() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<6>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField6( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<6>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField6(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<6>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField6(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<6>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField6() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<6>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField7() const {
  return !_reader.getPointerField(
      ::capnp::bounded<7>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField7() {
  return !_builder.getPointerField(
      ::capnp::bounded<7>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField7() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<7>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField7() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<7>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField7( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<7>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField7(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<7>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField7(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<7>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField7() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<7>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField8() const {
  return !_reader.getPointerField(
      ::capnp::bounded<8>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField8() {
  return !_builder.getPointerField(
      ::capnp::bounded<8>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField8() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<8>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField8() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<8>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField8( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<8>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField8(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<8>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField8(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<8>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField8() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<8>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField9() const {
  return !_reader.getPointerField(
      ::capnp::bounded<9>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField9() {
  return !_builder.getPointerField(
      ::capnp::bounded<9>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField9() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<9>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField9() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<9>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField9( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<9>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField9(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<9>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField9(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<9>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField9() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<9>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField10() const {
  return !_reader.getPointerField(
      ::capnp::bounded<10>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField10() {
  return !_builder.getPointerField(
      ::capnp::bounded<10>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField10() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<10>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField10() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<10>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField10( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<10>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField10(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<10>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField10(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<10>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField10() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<10>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField11() const {
  return !_reader.getPointerField(
      ::capnp::bounded<11>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField11() {
  return !_builder.getPointerField(
      ::capnp::bounded<11>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField11() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<11>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField11() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<11>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField11( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<11>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField11(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<11>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField11(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<11>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField11() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<11>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField12() const {
  return !_reader.getPointerField(
      ::capnp::bounded<12>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField12() {
  return !_builder.getPointerField(
      ::capnp::bounded<12>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField12() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<12>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField12() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<12>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField12( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<12>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField12(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<12>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField12(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<12>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField12() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<12>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField13() const {
  return !_reader.getPointerField(
      ::capnp::bounded<13>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField13() {
  return !_builder.getPointerField(
      ::capnp::bounded<13>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField13() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<13>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField13() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<13>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField13( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<13>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField13(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<13>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField13(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<13>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField13() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<13>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField14() const {
  return !_reader.getPointerField(
      ::capnp::bounded<14>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField14() {
  return !_builder.getPointerField(
      ::capnp::bounded<14>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField14() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<14>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField14() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<14>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField14( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<14>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField14(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<14>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField14(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<14>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField14() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<14>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField15() const {
  return !_reader.getPointerField(
      ::capnp::bounded<15>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField15() {
  return !_builder.getPointerField(
      ::capnp::bounded<15>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField15() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<15>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField15() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<15>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField15( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<15>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField15(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<15>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField15(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<15>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField15() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<15>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField16() const {
  return !_reader.getPointerField(
      ::capnp::bounded<16>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField16() {
  return !_builder.getPointerField(
      ::capnp::bounded<16>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField16() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<16>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField16() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<16>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField16( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<16>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField16(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<16>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField16(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<16>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField16() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<16>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField17() const {
  return !_reader.getPointerField(
      ::capnp::bounded<17>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField17() {
  return !_builder.getPointerField(
      ::capnp::bounded<17>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField17() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<17>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField17() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<17>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField17( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<17>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField17(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<17>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField17(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<17>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField17() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<17>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField18() const {
  return !_reader.getPointerField(
      ::capnp::bounded<18>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField18() {
  return !_builder.getPointerField(
      ::capnp::bounded<18>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField18() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<18>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField18() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<18>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField18( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<18>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField18(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<18>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField18(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<18>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField18() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<18>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField19() const {
  return !_reader.getPointerField(
      ::capnp::bounded<19>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField19() {
  return !_builder.getPointerField(
      ::capnp::bounded<19>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField19() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<19>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField19() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<19>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField19( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<19>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField19(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<19>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField19(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<19>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField19() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<19>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField20() const {
  return !_reader.getPointerField(
      ::capnp::bounded<20>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField20() {
  return !_builder.getPointerField(
      ::capnp::bounded<20>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField20() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<20>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField20() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<20>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField20( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<20>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField20(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<20>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField20(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<20>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField20() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<20>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField21() const {
  return !_reader.getPointerField(
      ::capnp::bounded<21>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField21() {
  return !_builder.getPointerField(
      ::capnp::bounded<21>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField21() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<21>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField21() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<21>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField21( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<21>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField21(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<21>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField21(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<21>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField21() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<21>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField22() const {
  return !_reader.getPointerField(
      ::capnp::bounded<22>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField22() {
  return !_builder.getPointerField(
      ::capnp::bounded<22>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField22() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<22>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField22() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<22>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField22( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<22>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField22(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<22>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField22(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<22>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField22() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<22>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField23() const {
  return !_reader.getPointerField(
      ::capnp::bounded<23>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField23() {
  return !_builder.getPointerField(
      ::capnp::bounded<23>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField23() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<23>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField23() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<23>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField23( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<23>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField23(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<23>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField23(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<23>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField23() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<23>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField24() const {
  return !_reader.getPointerField(
      ::capnp::bounded<24>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField24() {
  return !_builder.getPointerField(
      ::capnp::bounded<24>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField24() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<24>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField24() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<24>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField24( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<24>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField24(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<24>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField24(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<24>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField24() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<24>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField25() const {
  return !_reader.getPointerField(
      ::capnp::bounded<25>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField25() {
  return !_builder.getPointerField(
      ::capnp::bounded<25>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField25() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<25>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField25() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<25>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField25( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<25>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField25(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<25>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField25(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<25>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField25() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<25>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField26() const {
  return !_reader.getPointerField(
      ::capnp::bounded<26>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField26() {
  return !_builder.getPointerField(
      ::capnp::bounded<26>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField26() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<26>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField26() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<26>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField26( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<26>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField26(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<26>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField26(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<26>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField26() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<26>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField27() const {
  return !_reader.getPointerField(
      ::capnp::bounded<27>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField27() {
  return !_builder.getPointerField(
      ::capnp::bounded<27>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField27() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<27>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField27() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<27>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField27( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<27>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField27(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<27>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField27(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<27>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField27() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<27>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField28() const {
  return !_reader.getPointerField(
      ::capnp::bounded<28>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField28() {
  return !_builder.getPointerField(
      ::capnp::bounded<28>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField28() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<28>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField28() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<28>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField28( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<28>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField28(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<28>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField28(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<28>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField28() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<28>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField29() const {
  return !_reader.getPointerField(
      ::capnp::bounded<29>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField29() {
  return !_builder.getPointerField(
      ::capnp::bounded<29>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField29() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<29>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField29() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<29>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField29( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<29>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField29(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<29>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField29(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<29>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField29() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<29>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField30() const {
  return !_reader.getPointerField(
      ::capnp::bounded<30>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField30() {
  return !_builder.getPointerField(
      ::capnp::bounded<30>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField30() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<30>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField30() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<30>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField30( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<30>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField30(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<30>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField30(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<30>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField30() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<30>() * ::capnp::POINTERS));
}

inline bool WideUserData::Reader::hasField31() const {
  return !_reader.getPointerField(
      ::capnp::bounded<31>() * ::capnp::POINTERS).isNull();
}
inline bool WideUserData::Builder::hasField31() {
  return !_builder.getPointerField(
      ::capnp::bounded<31>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader WideUserData::Reader::getField31() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<31>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder WideUserData::Builder::getField31() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<31>() * ::capnp::POINTERS));
}
inline void WideUserData::Builder::setField31( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<31>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder WideUserData::Builder::initField31(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<31>() * ::capnp::POINTERS), size);
}
inline void WideUserData::Builder::adoptField31(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<31>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> WideUserData::Builder::disownField31() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<31>() * ::capnp::POINTERS));
}


CAPNP_END_HEADER

